modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="assassinsoath"
version="${mod_version}"
displayName="The Assassin's Oath"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.assassinsoath]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.assassinsoath]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.assassinsoath]]
   modId="epicfight"
   mandatory=true
   versionRange="*"
   ordering="NONE"
   side="BOTH"
