/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 */
import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class feb {
    private static final fei a = new fei(0.008f);
    private static final fei b = new fei(1.0f);
    private static final fei c = new fei(0.5f);

    public static Map<fec, fek> a() {
        ImmutableMap.Builder $$0 = ImmutableMap.builder();
        fek $$12 = fek.a(fbs.a(fei.a, 0.0f), 64, 64);
        fek $$22 = fek.a(fbr.a(b), 64, 32);
        fek $$3 = fek.a(fbr.a(new fei(1.02f)), 64, 32);
        fek $$4 = fek.a(fbr.a(c), 64, 32);
        fek $$5 = fca.b();
        fek $$6 = fdb.c();
        fek $$7 = fek.a(fbq.a(fei.a), 64, 64);
        fek $$8 = fbt.b();
        fek $$9 = fay.c();
        fek $$10 = fek.a(fcd.a(fei.a), 64, 32);
        fek $$11 = fek.a(fcj.a(fei.a), 64, 64);
        fek $$122 = fek.a(fci.a(), 64, 64);
        fek $$13 = fdb.b();
        fek $$14 = fby.a(fei.a);
        fek $$15 = fdi.b();
        fek $$16 = fbp.c();
        fek $$17 = fda.c();
        fek $$18 = fek.a(fdq.b(), 64, 64);
        fek $$19 = fdg.b();
        $$0.put((Object)fed.a, (Object)fae.b());
        $$0.put((Object)fed.b, (Object)fai.c());
        $$0.put((Object)fed.c, (Object)fah.a(c));
        $$0.put((Object)fed.d, (Object)fah.a(b));
        $$0.put((Object)fed.e, (Object)faj.c());
        $$0.put((Object)fed.f, (Object)flp.a());
        $$0.put((Object)fed.g, (Object)fak.b());
        $$0.put((Object)fed.h, (Object)flr.c());
        $$0.put((Object)fed.i, (Object)flr.b());
        $$0.put((Object)fed.j, (Object)fal.c());
        $$0.put((Object)fed.k, (Object)fls.b());
        $$0.put((Object)fed.l, (Object)fam.b());
        $$0.put((Object)fed.m, (Object)fao.a());
        $$0.put((Object)fed.n, (Object)$$10);
        $$0.put((Object)fed.o, (Object)fek.a(fcd.a(new fei(0.01f)), 64, 32));
        $$0.put((Object)fed.p, (Object)fap.b());
        $$0.put((Object)fed.q, (Object)$$19);
        $$0.put((Object)fed.r, (Object)fma.b());
        $$0.put((Object)fed.s, (Object)$$5);
        $$0.put((Object)fed.t, (Object)fau.c());
        $$0.put((Object)fed.u, (Object)fav.b());
        $$0.put((Object)fed.v, (Object)$$5);
        $$0.put((Object)fed.x, (Object)fmb.b());
        $$0.put((Object)fed.z, (Object)fmb.c());
        $$0.put((Object)fed.y, (Object)fmb.d());
        $$0.put((Object)fed.w, (Object)fmb.e());
        $$0.put((Object)fed.A, (Object)$$9);
        $$0.put((Object)fed.B, (Object)faz.a(fei.a));
        $$0.put((Object)fed.C, (Object)faz.a(new fei(2.0f)));
        $$0.put((Object)fed.D, (Object)$$6);
        $$0.put((Object)fed.E, (Object)fmc.b());
        $$0.put((Object)fed.F, (Object)fmc.c());
        $$0.put((Object)fed.G, (Object)fba.b());
        $$0.put((Object)fed.H, (Object)fat.c());
        $$0.put((Object)fed.I, (Object)fma.d());
        $$0.put((Object)fed.J, (Object)fma.c());
        $$0.put((Object)fed.K, (Object)fdy.a());
        $$0.put((Object)fed.L, (Object)fbb.a(fei.a));
        $$0.put((Object)fed.M, (Object)$$4);
        $$0.put((Object)fed.N, (Object)$$4);
        $$0.put((Object)fed.O, (Object)fbb.a(new fei(0.25f)));
        $$0.put((Object)fed.P, (Object)fbm.b());
        $$0.put((Object)fed.Q, (Object)fbc.c());
        $$0.put((Object)fed.R, (Object)fbd.c());
        $$0.put((Object)fed.S, (Object)fbe.b());
        $$0.put((Object)fed.T, (Object)fot.a());
        $$0.put((Object)fed.U, (Object)fos.a());
        $$0.put((Object)fed.V, (Object)$$8);
        $$0.put((Object)fed.W, (Object)fbg.b());
        $$0.put((Object)fed.X, (Object)fbh.c());
        $$0.put((Object)fed.Y, (Object)fbi.b());
        $$0.put((Object)fed.Z, (Object)$$5);
        $$0.put((Object)fed.aa, (Object)fbj.b());
        $$0.put((Object)fed.ab, (Object)$$12);
        $$0.put((Object)fed.ac, (Object)$$4);
        $$0.put((Object)fed.ad, (Object)$$22);
        $$0.put((Object)fed.ae, (Object)fdh.b());
        $$0.put((Object)fed.af, (Object)fbl.c());
        $$0.put((Object)fed.ag, (Object)fbm.b());
        $$0.put((Object)fed.ah, (Object)$$16);
        $$0.put((Object)fed.ai, (Object)$$5);
        $$0.put((Object)fed.aj, (Object)$$7);
        $$0.put((Object)fed.ak, (Object)fek.a(fbq.a(new fei(0.1f)), 64, 64));
        $$0.put((Object)fed.al, (Object)$$12);
        $$0.put((Object)fed.am, (Object)$$4);
        $$0.put((Object)fed.an, (Object)$$22);
        $$0.put((Object)fed.ao, (Object)$$8);
        $$0.put((Object)fed.ap, (Object)fbu.b());
        $$0.put((Object)fed.aq, (Object)fbw.b());
        $$0.put((Object)fed.ar, (Object)$$14);
        $$0.put((Object)fed.as, (Object)fby.a(new fei(0.5f)));
        $$0.put((Object)fed.at, (Object)fbz.b());
        $$0.put((Object)fed.au, (Object)fbv.b());
        $$0.put((Object)fed.av, (Object)$$5);
        $$0.put((Object)fed.aw, (Object)$$9);
        $$0.put((Object)fed.ax, (Object)fat.c());
        $$0.put((Object)fed.ay, (Object)$$10);
        $$0.put((Object)fed.az, (Object)fce.c());
        $$0.put((Object)fed.aA, (Object)fcf.b());
        $$0.put((Object)fed.aB, (Object)fcg.b());
        $$0.put((Object)fed.aC, (Object)fch.a(fei.a));
        $$0.put((Object)fed.aK, (Object)fch.a(new fei(0.5f)));
        $$0.put((Object)fed.aD, (Object)$$11);
        $$0.put((Object)fed.aI, (Object)$$4);
        $$0.put((Object)fed.aJ, (Object)$$3);
        $$0.put((Object)fed.aE, (Object)$$11);
        $$0.put((Object)fed.aF, (Object)$$4);
        $$0.put((Object)fed.aG, (Object)$$3);
        $$0.put((Object)fed.aH, (Object)$$122);
        $$0.put((Object)fed.aL, (Object)$$8);
        $$0.put((Object)fed.aM, (Object)fek.a(fck.a(fei.a, false), 64, 64));
        $$0.put((Object)fed.aN, (Object)$$13);
        $$0.put((Object)fed.aO, (Object)$$4);
        $$0.put((Object)fed.aP, (Object)$$22);
        $$0.put((Object)fed.aQ, (Object)fek.a(fck.a(fei.a, true), 64, 64));
        $$0.put((Object)fed.aR, (Object)$$4);
        $$0.put((Object)fed.aS, (Object)$$22);
        $$0.put((Object)fed.aT, (Object)ftn.a());
        $$0.put((Object)fed.aU, (Object)fcl.c());
        $$0.put((Object)fed.aV, (Object)fcm.b());
        $$0.put((Object)fed.aW, (Object)fcn.b());
        $$0.put((Object)fed.aX, (Object)fco.b());
        $$0.put((Object)fed.aY, (Object)fcq.a());
        $$0.put((Object)fed.aZ, (Object)fcs.b());
        $$0.put((Object)fed.ba, (Object)fct.b());
        $$0.put((Object)fed.bb, (Object)fcv.c());
        $$0.put((Object)fed.bc, (Object)fcu.c());
        $$0.put((Object)fed.bd, (Object)fcw.a());
        $$0.put((Object)fed.be, (Object)fcy.a());
        $$0.put((Object)fed.bf, (Object)fcx.b());
        $$0.put((Object)fed.bg, (Object)fcz.b());
        $$0.put((Object)fed.bh, (Object)$$17);
        $$0.put((Object)fed.bj, (Object)$$4);
        $$0.put((Object)fed.bk, (Object)$$22);
        $$0.put((Object)fed.bi, (Object)$$7);
        $$0.put((Object)fed.bl, (Object)$$6);
        $$0.put((Object)fed.bm, (Object)fdd.c());
        $$0.put((Object)fed.bn, (Object)fdd.b());
        $$0.put((Object)fed.bo, (Object)fde.b());
        $$0.put((Object)fed.bp, (Object)fdf.b());
        $$0.put((Object)fed.bq, (Object)$$5);
        $$0.put((Object)fed.br, (Object)$$19);
        $$0.put((Object)fed.bs, (Object)fdh.b());
        $$0.put((Object)fed.bt, (Object)$$17);
        $$0.put((Object)fed.bu, (Object)$$4);
        $$0.put((Object)fed.bv, (Object)$$22);
        $$0.put((Object)fed.bw, (Object)fek.a(fbs.a(new fei(0.25f), 0.0f), 64, 32));
        $$0.put((Object)fed.bx, (Object)$$15);
        $$0.put((Object)fed.by, (Object)$$15);
        $$0.put((Object)fed.bz, (Object)fdj.c());
        $$0.put((Object)fed.bA, (Object)$$5);
        $$0.put((Object)fed.bB, (Object)$$14);
        $$0.put((Object)fed.bC, (Object)fdk.a());
        $$0.put((Object)fed.bD, (Object)fdm.a(fei.a));
        $$0.put((Object)fed.bE, (Object)fdm.a(a));
        $$0.put((Object)fed.bF, (Object)fdl.a(fei.a));
        $$0.put((Object)fed.bG, (Object)fdl.a(a));
        $$0.put((Object)fed.bH, (Object)fdn.c());
        $$0.put((Object)fed.bI, (Object)fdo.b());
        $$0.put((Object)fed.bJ, (Object)$$18);
        $$0.put((Object)fed.bK, (Object)$$8);
        $$0.put((Object)fed.bL, (Object)fdr.b());
        $$0.put((Object)fed.bM, (Object)$$18);
        $$0.put((Object)fed.bN, (Object)fdt.c());
        $$0.put((Object)fed.bO, (Object)fdu.a(fei.a));
        $$0.put((Object)fed.bP, (Object)fdu.a(c));
        $$0.put((Object)fed.bU, (Object)frz.a());
        $$0.put((Object)fed.bQ, (Object)$$17);
        $$0.put((Object)fed.bR, (Object)$$4);
        $$0.put((Object)fed.bS, (Object)$$22);
        $$0.put((Object)fed.bT, (Object)$$6);
        $$0.put((Object)fed.bV, (Object)fdv.c());
        $$0.put((Object)fed.bW, (Object)$$16);
        $$0.put((Object)fed.bX, (Object)$$12);
        $$0.put((Object)fed.ca, (Object)$$4);
        $$0.put((Object)fed.cb, (Object)$$22);
        $$0.put((Object)fed.bY, (Object)$$13);
        $$0.put((Object)fed.bZ, (Object)$$7);
        $$0.put((Object)fed.cc, (Object)fdx.c());
        $$0.put((Object)fed.cd, (Object)fdx.a(c));
        $$0.put((Object)fed.ce, (Object)fdx.a(b));
        $$0.put((Object)fed.cf, (Object)$$11);
        $$0.put((Object)fed.cg, (Object)$$4);
        $$0.put((Object)fed.ch, (Object)$$3);
        fek $$20 = fan.a();
        fek $$21 = far.e();
        fek $$222 = fcr.b();
        fek $$23 = fas.a();
        for (cah.b $$24 : cah.b.values()) {
            if ($$24 == cah.b.i) {
                $$0.put((Object)fed.c($$24), (Object)$$222);
                $$0.put((Object)fed.d($$24), (Object)$$23);
                continue;
            }
            $$0.put((Object)fed.c($$24), (Object)$$20);
            $$0.put((Object)fed.d($$24), (Object)$$21);
        }
        fek $$25 = fmi.f();
        ddo.a().forEach($$2 -> $$0.put((Object)fed.a($$2), (Object)$$25));
        fek $$26 = fme.e();
        ddo.a().forEach($$2 -> $$0.put((Object)fed.b($$2), (Object)$$26));
        ImmutableMap $$27 = $$0.build();
        List $$28 = fed.a().filter($$1 -> !$$27.containsKey($$1)).collect(Collectors.toList());
        if (!$$28.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + $$28);
        }
        return $$27;
    }
}

