/*
 * Decompiled with CFR 0.152.
 */
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class kg
extends ka {
    private static final float[] h = new float[]{0.025f, 0.027777778f, 0.03125f, 0.041666668f, 0.1f};
    private static final Set<cfu> i = Stream.of(cpo.fA, cpo.fO, cpo.mX, cpo.gE, cpo.gG, cpo.gK, cpo.gI, cpo.gM, cpo.gO, cpo.gQ, cpo.kP, cpo.lf, cpo.lb, cpo.lc, cpo.kZ, cpo.kX, cpo.ld, cpo.kT, cpo.kY, cpo.kV, cpo.kS, cpo.kR, cpo.kW, cpo.la, cpo.le, cpo.kQ, cpo.kU).map(cml::k).collect(Collectors.toSet());

    public kg() {
        super(i, cay.c.a());
    }

    @Override
    protected void b() {
        this.t(cpo.c);
        this.t(cpo.d);
        this.t(cpo.e);
        this.t(cpo.f);
        this.t(cpo.g);
        this.t(cpo.h);
        this.t(cpo.j);
        this.t(cpo.k);
        this.t(cpo.m);
        this.t(cpo.n);
        this.t(cpo.o);
        this.t(cpo.p);
        this.t(cpo.q);
        this.t(cpo.r);
        this.t(cpo.t);
        this.t(cpo.u);
        this.t(cpo.s);
        this.t(cpo.v);
        this.t(cpo.w);
        this.a(cpo.so, this::u);
        this.t(cpo.x);
        this.t(cpo.y);
        this.t(cpo.z);
        this.t(cpo.A);
        this.t(cpo.B);
        this.t(cpo.D);
        this.t(cpo.C);
        this.t(cpo.I);
        this.a(cpo.J, kg.a());
        this.a(cpo.M, kg.a());
        this.t(cpo.K);
        this.t(cpo.U);
        this.t(cpo.V);
        this.t(cpo.W);
        this.t(cpo.X);
        this.t(cpo.Y);
        this.t(cpo.aa);
        this.t(cpo.Z);
        this.t(cpo.ae);
        this.t(cpo.al);
        this.t(cpo.af);
        this.t(cpo.ag);
        this.t(cpo.ah);
        this.t(cpo.ai);
        this.t(cpo.ak);
        this.t(cpo.am);
        this.t(cpo.aj);
        this.t(cpo.an);
        this.t(cpo.ok);
        this.t(cpo.ot);
        this.t(cpo.ao);
        this.t(cpo.ap);
        this.t(cpo.aq);
        this.t(cpo.ar);
        this.t(cpo.as);
        this.t(cpo.au);
        this.t(cpo.av);
        this.t(cpo.at);
        this.t(cpo.aw);
        this.t(cpo.ax);
        this.t(cpo.ay);
        this.t(cpo.az);
        this.t(cpo.aA);
        this.t(cpo.aC);
        this.t(cpo.aD);
        this.t(cpo.aB);
        this.t(cpo.ov);
        this.t(cpo.om);
        this.t(cpo.aO);
        this.t(cpo.aP);
        this.t(cpo.aT);
        this.t(cpo.aV);
        this.t(cpo.aW);
        this.t(cpo.aX);
        this.t(cpo.aY);
        this.t(cpo.bp);
        this.t(cpo.bq);
        this.t(cpo.br);
        this.t(cpo.by);
        this.t(cpo.bA);
        this.t(cpo.bB);
        this.t(cpo.bC);
        this.t(cpo.bD);
        this.t(cpo.bE);
        this.t(cpo.bF);
        this.t(cpo.bG);
        this.t(cpo.bH);
        this.t(cpo.bI);
        this.t(cpo.bJ);
        this.t(cpo.bK);
        this.t(cpo.bL);
        this.t(cpo.bM);
        this.t(cpo.bN);
        this.t(cpo.bO);
        this.t(cpo.bP);
        this.t(cpo.bR);
        this.t(cpo.bT);
        this.t(cpo.bS);
        this.t(cpo.bU);
        this.t(cpo.bV);
        this.t(cpo.bW);
        this.t(cpo.bX);
        this.t(cpo.bY);
        this.t(cpo.bZ);
        this.t(cpo.ca);
        this.t(cpo.cb);
        this.t(cpo.cc);
        this.t(cpo.cd);
        this.t(cpo.ce);
        this.t(cpo.cf);
        this.t(cpo.cg);
        this.t(cpo.ch);
        this.t(cpo.ci);
        this.t(cpo.cj);
        this.t(cpo.cn);
        this.t(cpo.co);
        this.t(cpo.pk);
        this.t(cpo.cp);
        this.t(cpo.cu);
        this.t(cpo.hS);
        this.t(cpo.hT);
        this.t(cpo.hU);
        this.t(cpo.cw);
        this.t(cpo.cz);
        this.t(cpo.cA);
        this.t(cpo.cE);
        this.t(cpo.cF);
        this.t(cpo.cG);
        this.t(cpo.cH);
        this.t(cpo.cJ);
        this.t(cpo.cK);
        this.t(cpo.cL);
        this.t(cpo.cI);
        this.t(cpo.cM);
        this.t(cpo.da);
        this.t(cpo.db);
        this.t(cpo.dc);
        this.t(cpo.dd);
        this.t(cpo.de);
        this.t(cpo.df);
        this.t(cpo.dg);
        this.t(cpo.dj);
        this.t(cpo.dh);
        this.t(cpo.di);
        this.t(cpo.dk);
        this.t(cpo.cO);
        this.t(cpo.cP);
        this.t(cpo.cQ);
        this.t(cpo.dw);
        this.t(cpo.dx);
        this.t(cpo.dz);
        this.t(cpo.dA);
        this.t(cpo.dB);
        this.t(cpo.dC);
        this.t(cpo.dD);
        this.t(cpo.dF);
        this.t(cpo.dG);
        this.t(cpo.dE);
        this.t(cpo.dH);
        this.t(cpo.dK);
        this.t(cpo.dM);
        this.t(cpo.dQ);
        this.t(cpo.dS);
        this.t(cpo.dT);
        this.t(cpo.dU);
        this.t(cpo.kj);
        this.t(cpo.kk);
        this.t(cpo.dV);
        this.t(cpo.dW);
        this.t(cpo.dX);
        this.t(cpo.dY);
        this.t(cpo.dZ);
        this.t(cpo.ea);
        this.t(cpo.sd);
        this.t(cpo.eb);
        this.t(cpo.ef);
        this.t(cpo.eg);
        this.t(cpo.ei);
        this.t(cpo.ez);
        this.t(cpo.eA);
        this.t(cpo.eB);
        this.t(cpo.eC);
        this.t(cpo.eD);
        this.t(cpo.eF);
        this.t(cpo.eG);
        this.t(cpo.eE);
        this.t(cpo.eH);
        this.t(cpo.eI);
        this.t(cpo.eJ);
        this.t(cpo.eK);
        this.t(cpo.eL);
        this.t(cpo.eX);
        this.t(cpo.fh);
        this.t(cpo.kb);
        this.t(cpo.kc);
        this.t(cpo.fi);
        this.t(cpo.fj);
        this.t(cpo.fm);
        this.t(cpo.fn);
        this.t(cpo.fo);
        this.t(cpo.fp);
        this.t(cpo.ft);
        this.t(cpo.fz);
        this.t(cpo.fB);
        this.t(cpo.fD);
        this.t(cpo.fH);
        this.t(cpo.fJ);
        this.t(cpo.fK);
        this.t(cpo.fL);
        this.t(cpo.fM);
        this.t(cpo.fP);
        this.t(cpo.fQ);
        this.t(cpo.fR);
        this.t(cpo.gv);
        this.t(cpo.gw);
        this.t(cpo.gx);
        this.t(cpo.gy);
        this.t(cpo.gz);
        this.t(cpo.gB);
        this.t(cpo.gC);
        this.t(cpo.gA);
        this.t(cpo.gD);
        this.t(cpo.gE);
        this.t(cpo.gG);
        this.t(cpo.gI);
        this.t(cpo.gM);
        this.t(cpo.gO);
        this.t(cpo.gQ);
        this.t(cpo.gS);
        this.t(cpo.gT);
        this.t(cpo.gU);
        this.t(cpo.gW);
        this.t(cpo.gX);
        this.t(cpo.gY);
        this.t(cpo.gZ);
        this.t(cpo.ha);
        this.t(cpo.hd);
        this.t(cpo.he);
        this.t(cpo.hf);
        this.t(cpo.hg);
        this.t(cpo.hh);
        this.t(cpo.hj);
        this.t(cpo.hk);
        this.t(cpo.hl);
        this.t(cpo.hm);
        this.t(cpo.hn);
        this.t(cpo.ho);
        this.t(cpo.hp);
        this.t(cpo.hq);
        this.t(cpo.hr);
        this.t(cpo.hs);
        this.t(cpo.ht);
        this.t(cpo.hu);
        this.t(cpo.hv);
        this.t(cpo.hw);
        this.t(cpo.hx);
        this.t(cpo.hy);
        this.t(cpo.hP);
        this.t(cpo.hR);
        this.t(cpo.hQ);
        this.t(cpo.hV);
        this.t(cpo.hY);
        this.t(cpo.hZ);
        this.t(cpo.ia);
        this.t(cpo.ib);
        this.t(cpo.ic);
        this.t(cpo.id);
        this.t(cpo.ie);
        this.t(cpo.ij);
        this.t(cpo.ik);
        this.t(cpo.il);
        this.t(cpo.im);
        this.t(cpo.in);
        this.t(cpo.io);
        this.t(cpo.ip);
        this.t(cpo.iq);
        this.t(cpo.ir);
        this.t(cpo.is);
        this.t(cpo.it);
        this.t(cpo.iu);
        this.t(cpo.iv);
        this.t(cpo.iw);
        this.t(cpo.ix);
        this.t(cpo.iy);
        this.t(cpo.iz);
        this.t(cpo.iA);
        this.t(cpo.iB);
        this.t(cpo.jp);
        this.t(cpo.jq);
        this.t(cpo.jr);
        this.t(cpo.js);
        this.t(cpo.jR);
        this.t(cpo.jS);
        this.t(cpo.jT);
        this.t(cpo.jU);
        this.t(cpo.jV);
        this.t(cpo.jW);
        this.t(cpo.jX);
        this.t(cpo.jY);
        this.t(cpo.ka);
        this.t(cpo.jZ);
        this.t(cpo.kd);
        this.t(cpo.ke);
        this.t(cpo.kf);
        this.t(cpo.kg);
        this.t(cpo.ki);
        this.t(cpo.kh);
        this.t(cpo.kt);
        this.t(cpo.kw);
        this.t(cpo.kx);
        this.t(cpo.ky);
        this.t(cpo.kz);
        this.t(cpo.kJ);
        this.t(cpo.kK);
        this.t(cpo.kL);
        this.t(cpo.kM);
        this.t(cpo.kO);
        this.t(cpo.pd);
        this.t(cpo.lg);
        this.t(cpo.lh);
        this.t(cpo.li);
        this.t(cpo.lj);
        this.t(cpo.lk);
        this.t(cpo.ll);
        this.t(cpo.lm);
        this.t(cpo.ln);
        this.t(cpo.lo);
        this.t(cpo.lp);
        this.t(cpo.lq);
        this.t(cpo.lr);
        this.t(cpo.ls);
        this.t(cpo.lt);
        this.t(cpo.lu);
        this.t(cpo.lv);
        this.t(cpo.lw);
        this.t(cpo.lx);
        this.t(cpo.ly);
        this.t(cpo.lz);
        this.t(cpo.lA);
        this.t(cpo.lB);
        this.t(cpo.lC);
        this.t(cpo.lD);
        this.t(cpo.lE);
        this.t(cpo.lF);
        this.t(cpo.lG);
        this.t(cpo.lH);
        this.t(cpo.lI);
        this.t(cpo.lJ);
        this.t(cpo.lK);
        this.t(cpo.lL);
        this.t(cpo.lM);
        this.t(cpo.lN);
        this.t(cpo.lO);
        this.t(cpo.lP);
        this.t(cpo.lQ);
        this.t(cpo.lR);
        this.t(cpo.lS);
        this.t(cpo.lT);
        this.t(cpo.lU);
        this.t(cpo.lV);
        this.t(cpo.lW);
        this.t(cpo.lX);
        this.t(cpo.lY);
        this.t(cpo.lZ);
        this.t(cpo.ma);
        this.t(cpo.mb);
        this.t(cpo.mc);
        this.t(cpo.me);
        this.t(cpo.mh);
        this.t(cpo.mi);
        this.t(cpo.mj);
        this.t(cpo.mk);
        this.t(cpo.ml);
        this.t(cpo.mX);
        this.t(cpo.fA);
        this.t(cpo.mZ);
        this.t(cpo.ne);
        this.t(cpo.nf);
        this.t(cpo.ng);
        this.t(cpo.nh);
        this.t(cpo.ni);
        this.t(cpo.nj);
        this.t(cpo.nk);
        this.t(cpo.nl);
        this.t(cpo.nm);
        this.t(cpo.nn);
        this.t(cpo.no);
        this.t(cpo.np);
        this.t(cpo.nq);
        this.t(cpo.nr);
        this.t(cpo.nF);
        this.t(cpo.nG);
        this.t(cpo.nH);
        this.t(cpo.nI);
        this.t(cpo.nJ);
        this.t(cpo.nK);
        this.t(cpo.nM);
        this.t(cpo.nN);
        this.t(cpo.nO);
        this.t(cpo.nP);
        this.t(cpo.nQ);
        this.t(cpo.nR);
        this.t(cpo.nL);
        this.t(cpo.nT);
        this.t(cpo.nS);
        this.t(cpo.pg);
        this.t(cpo.ph);
        this.t(cpo.pl);
        this.t(cpo.pq);
        this.t(cpo.oj);
        this.t(cpo.ol);
        this.t(cpo.oo);
        this.t(cpo.op);
        this.t(cpo.os);
        this.t(cpo.ou);
        this.t(cpo.ox);
        this.t(cpo.oy);
        this.t(cpo.oE);
        this.t(cpo.oF);
        this.t(cpo.oJ);
        this.t(cpo.oL);
        this.t(cpo.oN);
        this.t(cpo.oP);
        this.t(cpo.oR);
        this.t(cpo.oT);
        this.t(cpo.oX);
        this.t(cpo.oI);
        this.t(cpo.oK);
        this.t(cpo.oM);
        this.t(cpo.oO);
        this.t(cpo.oQ);
        this.t(cpo.oS);
        this.t(cpo.oW);
        this.t(cpo.pi);
        this.t(cpo.pj);
        this.t(cpo.pr);
        this.t(cpo.pw);
        this.t(cpo.pA);
        this.t(cpo.ps);
        this.t(cpo.pt);
        this.t(cpo.pB);
        this.t(cpo.py);
        this.t(cpo.px);
        this.t(cpo.pv);
        this.t(cpo.pD);
        this.t(cpo.pF);
        this.t(cpo.pG);
        this.t(cpo.pH);
        this.t(cpo.pI);
        this.t(cpo.pJ);
        this.t(cpo.pK);
        this.t(cpo.eY);
        this.t(cpo.oq);
        this.t(cpo.oD);
        this.t(cpo.eN);
        this.t(cpo.ad);
        this.t(cpo.fk);
        this.t(cpo.qt);
        this.t(cpo.qA);
        this.t(cpo.qz);
        this.t(cpo.qB);
        this.s(cpo.qD);
        this.s(cpo.qE);
        this.s(cpo.qF);
        this.s(cpo.qH);
        this.a(cpo.qG, (cpn $$0) -> this.a((cpn)$$0, a));
        this.s(cpo.qI);
        this.s(cpo.cm);
        this.t(cpo.qM);
        this.t(cpo.qL);
        this.t(cpo.qK);
        this.t(cpo.qJ);
        this.t(cpo.qS);
        this.t(cpo.qR);
        this.t(cpo.qQ);
        this.t(cpo.qP);
        this.t(cpo.rb);
        this.t(cpo.rc);
        this.t(cpo.rd);
        this.t(cpo.re);
        this.t(cpo.ri);
        this.t(cpo.rg);
        this.t(cpo.rh);
        this.t(cpo.rf);
        this.t(cpo.rm);
        this.t(cpo.rl);
        this.t(cpo.rk);
        this.t(cpo.rj);
        this.t(cpo.qW);
        this.t(cpo.qV);
        this.t(cpo.qU);
        this.t(cpo.qT);
        this.t(cpo.rr);
        this.t(cpo.rs);
        this.t(cpo.rt);
        this.t(cpo.rw);
        this.t(cpo.ry);
        this.t(cpo.rx);
        this.t(cpo.rz);
        this.a(cpo.rA, this.o(cpo.rA));
        this.t(cpo.rC);
        this.t(cpo.rB);
        this.t(cpo.rG);
        this.t(cpo.rJ);
        this.t(cpo.rK);
        this.t(cpo.rM);
        this.t(cpo.rN);
        this.t(cpo.rO);
        this.t(cpo.rQ);
        this.t(cpo.rR);
        this.t(cpo.rS);
        this.t(cpo.rU);
        this.t(cpo.rV);
        this.t(cpo.rW);
        this.t(cpo.rY);
        this.t(cpo.rZ);
        this.t(cpo.sa);
        this.t(cpo.sb);
        this.t(cpo.se);
        this.t(cpo.sf);
        this.t(cpo.sg);
        this.t(cpo.sj);
        this.t(cpo.sk);
        this.t(cpo.sl);
        this.t(cpo.ac);
        this.t(cpo.ab);
        this.t(cpo.rH);
        this.t(cpo.eM);
        this.c(cpo.cC, (cml)cpo.j);
        this.c(cpo.fI, (cml)cgc.oE);
        this.c(cpo.kE, (cml)cpo.j);
        this.c(cpo.md, (cml)cpo.mc);
        this.c(cpo.mY, (cml)cpo.mZ);
        this.c(cpo.fu, (cml)cpo.ft);
        this.c(cpo.fv, (cml)cpo.ft);
        this.c(cpo.fw, (cml)cpo.ft);
        this.c(cpo.rD, (cml)cpo.rC);
        this.a(cpo.b, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.m));
        this.a(cpo.rI, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.rJ));
        this.a(cpo.i, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.j));
        this.a(cpo.l, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.j));
        this.a(cpo.fl, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.j));
        this.a(cpo.mm, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.mh));
        this.a(cpo.mn, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.mi));
        this.a(cpo.mo, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.mj));
        this.a(cpo.mp, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.mk));
        this.a(cpo.mq, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.ml));
        this.a(cpo.ow, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.dW));
        this.a(cpo.on, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.dW));
        this.a(cpo.cl, (cpn $$0) -> this.a((cpn)$$0, cgc.qb, edd.a(3.0f)));
        this.a(cpo.dR, (cpn $$0) -> this.a((cpn)$$0, cgc.pY, edd.a(4.0f)));
        this.a(cpo.fG, (cpn $$0) -> this.a((cpn)$$0, (cml)cpo.co, edd.a(8.0f)));
        this.a(cpo.dP, (cpn $$0) -> this.a((cpn)$$0, cgc.pO, edd.a(4.0f)));
        this.a(cpo.ku, this.a((cml)cgc.um, edi.a(0.0f, 1.0f)));
        this.r(cpo.fT);
        this.r(cpo.fU);
        this.r(cpo.fV);
        this.r(cpo.fW);
        this.r(cpo.fX);
        this.r(cpo.fZ);
        this.r(cpo.ga);
        this.r(cpo.fY);
        this.r(cpo.gb);
        this.r(cpo.gc);
        this.r(cpo.gd);
        this.r(cpo.ge);
        this.r(cpo.gf);
        this.r(cpo.gg);
        this.r(cpo.gh);
        this.r(cpo.gi);
        this.r(cpo.gj);
        this.r(cpo.gk);
        this.r(cpo.gl);
        this.r(cpo.gm);
        this.r(cpo.gn);
        this.r(cpo.go);
        this.r(cpo.gp);
        this.r(cpo.gq);
        this.r(cpo.gr);
        this.r(cpo.gs);
        this.r(cpo.na);
        this.r(cpo.pm);
        this.r(cpo.pn);
        this.r(cpo.po);
        this.r(cpo.pp);
        this.r(cpo.sh);
        this.r(cpo.si);
        this.r(cpo.fS);
        this.a(cpo.jt, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jH, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ju, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jv, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jw, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jx, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jz, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jA, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jy, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jB, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jC, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jJ, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jI, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ih, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jM, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ig, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.if, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jQ, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jN, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jO, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jF, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jP, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jG, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jK, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jD, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jE, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ns, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nt, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nu, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nv, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nw, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nx, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ny, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nz, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nA, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nB, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nC, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nD, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.nE, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.oG, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.oH, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.pu, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.pz, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.pE, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.qX, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.qY, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.qZ, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ra, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rn, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.ro, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rp, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rq, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rL, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rP, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rT, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.rX, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.jL, (cpn $$1) -> this.a((cpn)$$1));
        this.a(cpo.cN, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.kl, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.km, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.kn, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.ko, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.kq, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.kr, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.kp, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.ks, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.oV, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.oU, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.dy, (cpn $$1) -> this.q((cpn)$$1));
        this.a(cpo.bo, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bk, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bl, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bi, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bg, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bm, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bc, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bh, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.be, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bb, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bj, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.ba, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bf, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bn, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.aZ, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.bd, (cpn $$0) -> this.a((cpn)$$0, cpg.a, dco.a));
        this.a(cpo.iE, (cpn $$0) -> this.a((cpn)$$0, crr.a, dcx.b));
        this.a(cpo.iD, (cpn $$0) -> this.a((cpn)$$0, crr.a, dcx.b));
        this.a(cpo.iG, (cpn $$0) -> this.a((cpn)$$0, crr.a, dcx.b));
        this.a(cpo.iF, (cpn $$0) -> this.a((cpn)$$0, crr.a, dcx.b));
        this.a(cpo.ck, dzs.b().a(this.a((cml)cpo.ck, dzr.a().a(edd.a(1.0f)).a((eaf.a<?>)eac.a(cpo.ck).a(ecj.a(cpo.ck).a(cz.a.a().a(cxx.a, false)))))));
        this.a(cpo.fC, (cpn $$0) -> dzs.b().a(dzr.a().a(edd.a(1.0f)).a((eaf.a)this.a((cml)$$0, eac.a(cgc.qt).a((eaz.a)ebj.a(edd.a(3.0f)).a(ecj.a($$0).a(cz.a.a().a(cqt.b, 2))))))));
        this.a(cpo.mV, (cpn $$0) -> dzs.b().a(dzr.a().a(edd.a(1.0f)).a((eaf.a)this.a((cml)cpo.mV, eac.a($$0).a(List.of(Integer.valueOf(2), Integer.valueOf(3), Integer.valueOf(4)), (E $$1) -> ebj.a(edd.a($$1.intValue())).a(ecj.a($$0).a(cz.a.a().a(cwk.b, $$1.intValue()))))))));
        this.a(cpo.pc, (cpn $$0) -> dzs.b().a(dzr.a().a((eaf.a)this.a((cml)$$0, eac.a(cgc.vj)))).a(dzr.a().a(eac.a(cgc.qK)).a(ecj.a($$0).a(cz.a.a().a(cqw.d, 8)))));
        this.a(cpo.ru, (cpn $$0) -> ka.j($$0));
        this.a(cpo.rv, (cpn $$0) -> ka.j($$0));
        this.a(cpo.pL, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pM, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pN, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pO, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pP, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pQ, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pR, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pS, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pT, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pU, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pV, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pW, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pX, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pY, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.pZ, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.qa, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.qb, (cpn $$1) -> this.n((cpn)$$1));
        this.a(cpo.fO, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.fs, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.cv, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.aU, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.hi, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.fr, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.cD, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.hc, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.gV, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.nV, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.nW, (cpn $$1) -> this.b((cpn)$$1));
        this.a(cpo.nU, (cpn $$1) -> this.b((cpn)$$1));
        this.t(cpo.nX);
        this.t(cpo.nY);
        this.t(cpo.nZ);
        this.t(cpo.oa);
        this.t(cpo.ob);
        this.t(cpo.oc);
        this.a(cpo.od, this::a);
        this.a(cpo.oe, this::a);
        this.a(cpo.of, this::a);
        this.a(cpo.kP, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.lf, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.lb, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.lc, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kZ, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kX, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.ld, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kT, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kY, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kV, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kS, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kR, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kW, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.la, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.le, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kQ, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.kU, (cpn $$1) -> this.c((cpn)$$1));
        this.a(cpo.iY, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iU, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iV, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iS, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iQ, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iW, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iM, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iR, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iO, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iL, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iK, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iP, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iT, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iX, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iJ, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.iN, (cpn $$1) -> this.g((cpn)$$1));
        this.a(cpo.gK, (cpn $$0) -> dzs.b().a(this.a((cml)$$0, dzr.a().a(edd.a(1.0f)).a((eaf.a<?>)eac.a($$0).a(eaq.a(ecw.a).a("SkullOwner", "SkullOwner").a("note_block_sound", String.format(Locale.ROOT, "%s.%s", "BlockEntityTag", "note_block_sound")))))));
        this.a(cpo.pe, (cpn $$0) -> kg.h($$0));
        this.a(cpo.pf, (cpn $$0) -> kg.i($$0));
        this.a(cpo.aE, (cpn $$0) -> this.b((cpn)$$0, cpo.x, g));
        this.a(cpo.aF, (cpn $$0) -> this.a((cpn)$$0, cpo.y, g));
        this.a(cpo.aG, (cpn $$0) -> this.a((cpn)$$0, cpo.z, g));
        this.a(cpo.aH, (cpn $$0) -> this.a((cpn)$$0, cpo.A, h));
        this.a(cpo.aI, (cpn $$0) -> this.a((cpn)$$0, cpo.B, g));
        this.a(cpo.aK, (cpn $$0) -> this.b((cpn)$$0, cpo.D, g));
        this.a(cpo.aJ, (cpn $$0) -> this.a((cpn)$$0, cpo.C, g));
        this.a(cpo.aM, (cpn $$0) -> this.a((cpn)$$0, cpo.rx, g));
        this.a(cpo.aN, (cpn $$0) -> this.a((cpn)$$0, cpo.ry, g));
        ecj.a $$02 = ecj.a(cpo.kD).a(cz.a.a().a(cpi.b, 3));
        this.a(cpo.kD, this.a(cpo.kD, cgc.uq, cgc.ur, $$02));
        ecj.a $$12 = ecj.a(cpo.cB).a(cz.a.a().a(cre.d, 7));
        this.a(cpo.cB, this.a(cpo.cB, cgc.oI, cgc.oH, $$12));
        ecj.a $$2 = ecj.a(cpo.gt).a(cz.a.a().a(cqe.d, 7));
        ecj.a $$3 = ecj.a(cpo.E).a(cz.a.a().a(cuf.a, 4));
        this.a(cpo.E, this.a((cml)cpo.E, dzs.b().a(dzr.a().a($$3).a(eac.a(cgc.Q)))));
        this.a(cpo.kA, this.a((cml)cpo.kA, dzs.b().a(dzr.a().a(eac.a(cgc.uo)))));
        this.t(cpo.mg);
        this.a(cpo.kB, (cpn $$0) -> this.c());
        this.t(cpo.kC);
        this.a(cpo.kC, this.a((cml)cpo.kC, dzs.b().a(dzr.a().a((eaf.a<?>)eac.a(cgc.dc).a(ecj.a(cpo.kC).a(cz.a.a().a(crr.a, dcx.b)))))));
        this.a(cpo.gt, this.a((cml)cpo.gt, dzs.b().a(dzr.a().a(eac.a(cgc.tl))).a(dzr.a().a($$2).a((eaf.a<?>)eac.a(cgc.tl).a(eam.a(ckk.x, 0.5714286f, 3))))));
        ecj.a $$4 = ecj.a(cpo.gu).a(cz.a.a().a(cve.d, 7));
        this.a(cpo.gu, this.a((cml)cpo.gu, dzs.b().a(dzr.a().a(eac.a(cgc.tm))).a(dzr.a().a($$4).a((eaf.a<?>)eac.a(cgc.tm).a(eam.a(ckk.x, 0.5714286f, 3)))).a(dzr.a().a($$4).a((eaf.a<?>)eac.a(cgc.to).a(ecp.a(0.02f))))));
        this.a(cpo.oi, (cpn $$0) -> this.a((cml)$$0, dzs.b().a(dzr.a().a(ecj.a(cpo.oi).a(cz.a.a().a(cxr.b, 3))).a(eac.a(cgc.vv)).a(ebj.a(edi.a(2.0f, 3.0f))).a(eam.b(ckk.x))).a(dzr.a().a(ecj.a(cpo.oi).a(cz.a.a().a(cxr.b, 2))).a(eac.a(cgc.vv)).a(ebj.a(edi.a(1.0f, 2.0f))).a(eam.b(ckk.x)))));
        this.a(cpo.eU, (cpn $$0) -> this.b((cpn)$$0, (cml)cpo.cf));
        this.a(cpo.eV, (cpn $$0) -> this.b((cpn)$$0, (cml)cpo.cg));
        this.a(cpo.R, (cpn $$0) -> this.a((cpn)$$0, cgc.nI));
        this.a(cpo.S, (cpn $$0) -> this.a((cpn)$$0, cgc.nI));
        this.a(cpo.fE, (cpn $$0) -> this.a((cpn)$$0, cgc.nL));
        this.a(cpo.fF, (cpn $$0) -> this.a((cpn)$$0, cgc.nL));
        this.a(cpo.hb, (cpn $$0) -> this.a((cpn)$$0, cgc.nN));
        this.a(cpo.cx, (cpn $$0) -> this.a((cpn)$$0, cgc.nK));
        this.a(cpo.cy, (cpn $$0) -> this.a((cpn)$$0, cgc.nK));
        this.a(cpo.qN, (cpn $$1) -> this.d((cpn)$$1));
        this.a(cpo.qO, (cpn $$1) -> this.d((cpn)$$1));
        this.a(cpo.P, (cpn $$0) -> this.a((cpn)$$0, cgc.nP));
        this.a(cpo.Q, (cpn $$0) -> this.a((cpn)$$0, cgc.nP));
        this.a(cpo.N, (cpn $$0) -> this.a((cpn)$$0, cgc.nT));
        this.a(cpo.O, (cpn $$0) -> this.a((cpn)$$0, cgc.nT));
        this.a(cpo.T, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, ((eah.a)eac.a(cgc.rt).a(ebj.a(edi.a(2.0f, 6.0f)))).a(eam.a(ckk.x)))));
        this.a(cpo.aR, (cpn $$1) -> this.e((cpn)$$1));
        this.a(cpo.aS, (cpn $$1) -> this.e((cpn)$$1));
        this.a(cpo.bs, (cpn $$0) -> kg.c($$0, (eaf.a)this.a((cml)$$0, eac.a(cgc.oE))));
        this.a(cpo.bv, (cpn $$0) -> kg.b($$0, (eaf.a)this.a((cml)$$0, eac.a(cgc.oB).a(ebj.a(edi.a(0.0f, 2.0f))))));
        this.a(cpo.or, (cpn $$0) -> ka.b($$0));
        this.a(cpo.bw, (cpn $$0) -> ka.b($$0));
        this.a(cpo.ff, (cpn $$0) -> ka.b($$0));
        this.a(cpo.fg, (cpn $$0) -> this.a((cpn)$$0, c));
        this.a(cpo.rF, (cpn $$0) -> ka.b($$0));
        this.a(cpo.rE, (cpn $$0) -> ka.b($$0));
        this.a(cpo.aL, (cpn $$1) -> this.l((cpn)$$1));
        this.a(cpo.bx, kg.m(cpo.bw));
        this.a(cpo.iI, (cpn $$0) -> this.a((cpn)$$0, cpo.bu));
        this.a(cpo.iH, (cpn $$0) -> this.a((cpn)$$0, cpo.bt));
        this.a(cpo.fe, (cpn $$0) -> this.b((cpn)$$0, cgc.rk));
        this.a(cpo.fc, (cpn $$0) -> this.c((cpn)$$0, cgc.rk));
        this.a(cpo.fd, (cpn $$0) -> this.b((cpn)$$0, cgc.rj));
        this.a(cpo.fb, (cpn $$0) -> this.c((cpn)$$0, cgc.rj));
        this.a(cpo.kv, (cpn $$0) -> dzs.b().a(dzr.a().a(edd.a(1.0f)).a((eaf.a<?>)((eah.a)this.a((cml)$$0, eac.a($$0))).a(ecn.a(dzk.b.a)))));
        this.a(cpo.bu, (cpn $$1) -> this.k((cpn)$$1));
        this.a(cpo.bt, (cpn $$1) -> this.k((cpn)$$1));
        this.a(cpo.ed, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, ((eah.a)((eah.a)eac.a(cgc.qk).a(ebj.a(edi.a(2.0f, 4.0f)))).a(eam.b(ckk.x))).a(eax.a(dzj.a(1, 4))))));
        this.a(cpo.fa, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, ((eah.a)((eah.a)eac.a(cgc.rh).a(ebj.a(edi.a(3.0f, 7.0f)))).a(eam.b(ckk.x))).a(eax.a(dzj.c(9))))));
        this.a(cpo.dI, (cpn $$1) -> this.f((cpn)$$1));
        this.a(cpo.dJ, (cpn $$1) -> this.f((cpn)$$1));
        this.a(cpo.ii, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, ((eah.a)((eah.a)eac.a(cgc.tF).a(ebj.a(edi.a(2.0f, 3.0f)))).a(eam.b(ckk.x))).a(eax.a(dzj.a(1, 5))))));
        this.a(cpo.fq, (cpn $$0) -> dzs.b().a(this.a((cml)$$0, dzr.a().a(edd.a(1.0f)).a((eaf.a<?>)((eah.a)eac.a(cgc.ru).a((eaz.a)ebj.a(edi.a(2.0f, 4.0f)).a(ecj.a($$0).a(cz.a.a().a(cus.b, 3))))).a((eaz.a)eam.b(ckk.x).a(ecj.a($$0).a(cz.a.a().a(cus.b, 3))))))));
        this.a(cpo.dN, (cpn $$0) -> dzs.b().a(dzr.a().a(ecn.a(dzk.b.a)).a(dzw.a(new eaf.a[]{dzw.a(cww.b.a(), (E $$1) -> ((eah.a)eac.a(cgc.pO).a(ecj.a($$0).a(cz.a.a().a(cww.b, $$1.intValue())))).a(ebj.a(edd.a($$1.intValue())))).a(b), dzw.a(cww.b.a(), (E $$1) -> $$1 == 8 ? eac.a(cpo.dP) : ((eaf.a)eac.a(cpo.dN).a(ebj.a(edd.a($$1.intValue())))).a(ecj.a($$0).a(cz.a.a().a(cww.b, $$1.intValue()))))}))));
        this.a(cpo.L, (cpn $$0) -> kg.a($$0, this.a((cml)$$0, ((eah.a)eac.a(cgc.pi).a(eca.a(ckk.x, 0.1f, 0.14285715f, 0.25f, 1.0f))).a(eac.a($$0)))));
        this.a(cpo.og, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, eac.a(cgc.nJ).a(ebj.a(edd.a(2.0f))))));
        this.a(cpo.pC, (cpn $$0) -> kg.a($$0, this.a((cml)$$0, ((eah.a)((eaf.a)eac.a(cgc.rt).a(ebj.a(edi.a(2.0f, 5.0f)))).a(eca.a(ckk.x, 0.1f, 0.14285715f, 0.25f, 1.0f))).a(eac.a($$0)))));
        this.a(cpo.oh, (cpn $$0) -> kg.a($$0, (eaf.a)this.a((cml)$$0, eac.a(cgc.eT).a(ebj.a(edd.a(1.0f))))));
        this.a(cpo.qv, (cpn $$0) -> kg.a($$0, ((eah.a)((eaf.a)((eah.a)eac.a(cgc.nO).a(ebj.a(edd.a(4.0f)))).a(eam.a(ckk.x))).a(ecr.a(bz.a.a().a(ane.aC)))).a((eaf.a)this.a((cml)$$0, eac.a(cgc.nO).a(ebj.a(edd.a(2.0f)))))));
        this.s(cpo.qy);
        this.s(cpo.qx);
        this.s(cpo.qw);
        this.s(cpo.aQ);
        this.s(cpo.ej);
        this.s(cpo.ek);
        this.s(cpo.el);
        this.s(cpo.em);
        this.s(cpo.en);
        this.s(cpo.eo);
        this.s(cpo.ep);
        this.s(cpo.eq);
        this.s(cpo.er);
        this.s(cpo.es);
        this.s(cpo.et);
        this.s(cpo.eu);
        this.s(cpo.ev);
        this.s(cpo.ew);
        this.s(cpo.ex);
        this.s(cpo.ey);
        this.s(cpo.eZ);
        this.s(cpo.hz);
        this.s(cpo.hA);
        this.s(cpo.hB);
        this.s(cpo.hC);
        this.s(cpo.hD);
        this.s(cpo.hE);
        this.s(cpo.hF);
        this.s(cpo.hG);
        this.s(cpo.hH);
        this.s(cpo.hI);
        this.s(cpo.hJ);
        this.s(cpo.hK);
        this.s(cpo.hL);
        this.s(cpo.hM);
        this.s(cpo.hN);
        this.s(cpo.hO);
        this.s(cpo.dO);
        this.s(cpo.iC);
        this.s(cpo.mW);
        this.s(cpo.mf);
        this.s(cpo.eW);
        this.s(cpo.mr);
        this.s(cpo.ms);
        this.s(cpo.mt);
        this.s(cpo.mu);
        this.s(cpo.mv);
        this.s(cpo.mw);
        this.s(cpo.mx);
        this.s(cpo.my);
        this.s(cpo.mz);
        this.s(cpo.mA);
        this.s(cpo.mB);
        this.s(cpo.mC);
        this.s(cpo.mD);
        this.s(cpo.mE);
        this.s(cpo.mF);
        this.s(cpo.mG);
        this.s(cpo.mH);
        this.s(cpo.mI);
        this.s(cpo.mJ);
        this.s(cpo.mK);
        this.c(cpo.eO, cpo.b);
        this.c(cpo.eP, cpo.m);
        this.c(cpo.eQ, cpo.eI);
        this.c(cpo.eR, cpo.eJ);
        this.c(cpo.eS, cpo.eK);
        this.c(cpo.eT, cpo.eL);
        this.c(cpo.sc, cpo.rI);
        this.b(cpo.oz, cpo.oA);
        this.b(cpo.oB, cpo.oC);
        this.a(cpo.eh, kg.a());
        this.a(cpo.qc, kg.p(cpo.pL));
        this.a(cpo.qd, kg.p(cpo.pM));
        this.a(cpo.qe, kg.p(cpo.pN));
        this.a(cpo.qf, kg.p(cpo.pO));
        this.a(cpo.qg, kg.p(cpo.pP));
        this.a(cpo.qh, kg.p(cpo.pQ));
        this.a(cpo.qi, kg.p(cpo.pR));
        this.a(cpo.qj, kg.p(cpo.pS));
        this.a(cpo.qk, kg.p(cpo.pT));
        this.a(cpo.ql, kg.p(cpo.pU));
        this.a(cpo.qm, kg.p(cpo.pV));
        this.a(cpo.qn, kg.p(cpo.pW));
        this.a(cpo.qo, kg.p(cpo.pX));
        this.a(cpo.qp, kg.p(cpo.pY));
        this.a(cpo.qq, kg.p(cpo.pZ));
        this.a(cpo.qr, kg.p(cpo.qa));
        this.a(cpo.qs, kg.p(cpo.qb));
        this.a(cpo.kI, kg.a());
        this.a(cpo.ct, kg.a());
        this.a(cpo.cr, kg.a());
        this.a(cpo.cs, kg.a());
        this.a(cpo.ee, kg.a());
        this.a(cpo.qu, kg.a());
        this.a(cpo.qC, kg.a());
        this.a(cpo.sm, kg.a());
        this.a(cpo.sn, kg.a());
        this.a(cpo.J, kg.a());
        this.a(cpo.M, kg.a());
    }

    private dzs.a u(cpn $$0) {
        return dzs.b().a(dzr.a().a(edd.a(1.0f)).a(((eah.a)((eah.a)dzz.a(crj.a).a(ecr.a(bz.a.a().a(ane.aT)))).a(b)).a((eaf.a<?>)eac.a($$0).a(eaq.a(ecw.a).a("sherds", "BlockEntityTag.sherds")))));
    }

    private dzs.a c() {
        return this.a((cml)cpo.kB, dzs.b().a(dzr.a().a(dzw.a(cva.b.a(), (E $$0) -> {
            ecj.a $$1 = ecj.a(cpo.kB).a(cz.a.a().a(crr.a, dcx.b));
            ecj.a $$2 = ecj.a(cpo.kB).a(cz.a.a().a(cva.b, $$0.intValue()));
            if ($$0 == 4) {
                return ((eah.a)((eah.a)eac.a(cgc.dc).a($$2)).a($$1)).a(ebj.a(edd.a(1.0f)));
            }
            return ((eah.a)((eah.a)eac.a(cgc.up).a($$2)).a($$1)).a(ebj.a(edd.a(1.0f)));
        }))));
    }
}

