/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 */
import com.google.common.collect.ImmutableList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class mb
extends lr {
    private static final ImmutableList<cml> d = ImmutableList.of((Object)cgc.X, (Object)cgc.Y);
    private static final ImmutableList<cml> e = ImmutableList.of((Object)cgc.Z, (Object)cgc.aa, (Object)cgc.nP);
    private static final ImmutableList<cml> f = ImmutableList.of((Object)cgc.ab, (Object)cgc.ac, (Object)cgc.nR);
    private static final ImmutableList<cml> g = ImmutableList.of((Object)cgc.ad, (Object)cgc.ae, (Object)cgc.an, (Object)cgc.nT);
    private static final ImmutableList<cml> h = ImmutableList.of((Object)cgc.al, (Object)cgc.am);
    private static final ImmutableList<cml> i = ImmutableList.of((Object)cgc.aj, (Object)cgc.ak);
    private static final ImmutableList<cml> j = ImmutableList.of((Object)cgc.af, (Object)cgc.ag);
    private static final ImmutableList<cml> k = ImmutableList.of((Object)cgc.ah, (Object)cgc.ai);

    public mb(jk $$0) {
        super($$0);
    }

    @Override
    public CompletableFuture<?> a(jg $$0) {
        return CompletableFuture.allOf(super.a($$0), this.a($$0, lp.a, ae.a.b().a("impossible", new bw.a())));
    }

    @Override
    protected void a(Consumer<lo> $$0) {
        mb.a($$0, caw.a(cay.a));
        mb.a($$0, (cml)cpo.r, ane.v, 4);
        mb.b($$0, cpo.p, ane.u, 4);
        mb.b($$0, cpo.oE, ane.A, 4);
        mb.a($$0, (cml)cpo.t, ane.s, 4);
        mb.b($$0, cpo.q, ane.x, 4);
        mb.b($$0, cpo.n, ane.t, 4);
        mb.b($$0, cpo.o, ane.y, 4);
        mb.b($$0, cpo.oF, ane.B, 4);
        mb.b($$0, cpo.u, ane.z, 4);
        mb.a($$0, (cml)cpo.as, (cml)cpo.Y);
        mb.a($$0, (cml)cpo.aq, (cml)cpo.W);
        mb.a($$0, (cml)cpo.au, (cml)cpo.aa);
        mb.a($$0, (cml)cpo.ar, (cml)cpo.X);
        mb.a($$0, (cml)cpo.ao, (cml)cpo.U);
        mb.a($$0, (cml)cpo.ap, (cml)cpo.V);
        mb.a($$0, (cml)cpo.ou, (cml)cpo.os);
        mb.a($$0, (cml)cpo.ol, (cml)cpo.oj);
        mb.a($$0, (cml)cpo.av, (cml)cpo.ab);
        mb.a($$0, (cml)cpo.aA, (cml)cpo.ai);
        mb.a($$0, (cml)cpo.ay, (cml)cpo.ag);
        mb.a($$0, (cml)cpo.aC, (cml)cpo.ak);
        mb.a($$0, (cml)cpo.az, (cml)cpo.ah);
        mb.a($$0, (cml)cpo.aw, (cml)cpo.al);
        mb.a($$0, (cml)cpo.ax, (cml)cpo.af);
        mb.a($$0, (cml)cpo.ov, (cml)cpo.ot);
        mb.a($$0, (cml)cpo.om, (cml)cpo.ok);
        mb.a($$0, (cml)cpo.aD, (cml)cpo.am);
        mb.b($$0, (cml)cgc.nq, cpo.r);
        mb.b($$0, (cml)cgc.nm, cpo.p);
        mb.b($$0, (cml)cgc.nu, cpo.t);
        mb.b($$0, (cml)cgc.no, cpo.q);
        mb.b($$0, (cml)cgc.ni, cpo.n);
        mb.b($$0, (cml)cgc.nk, cpo.o);
        mb.b($$0, (cml)cgc.nw, cpo.u);
        List<cfu> $$12 = List.of(cgc.qJ, cgc.qF, cgc.qG, cgc.qD, cgc.qB, cgc.qH, cgc.qx, cgc.qC, cgc.qz, cgc.qw, cgc.qv, cgc.qA, cgc.qE, cgc.qI, cgc.qy, cgc.qu);
        List<cfu> $$22 = List.of(cgc.cN, cgc.cJ, cgc.cK, cgc.cH, cgc.cF, cgc.cL, cgc.cB, cgc.cG, cgc.cD, cgc.cA, cgc.cz, cgc.cE, cgc.cI, cgc.cM, cgc.cC, cgc.cy);
        List<cfu> $$3 = List.of(cgc.rd, cgc.qZ, cgc.ra, cgc.qX, cgc.qV, cgc.rb, cgc.qR, cgc.qW, cgc.qT, cgc.qQ, cgc.qP, cgc.qU, cgc.qY, cgc.rc, cgc.qS, cgc.qO);
        List<cfu> $$4 = List.of(cgc.hx, cgc.ht, cgc.hu, cgc.hr, cgc.hp, cgc.hv, cgc.hl, cgc.hq, cgc.hn, cgc.hk, cgc.hj, cgc.ho, cgc.hs, cgc.hw, cgc.hm, cgc.hi);
        mb.a($$0, $$12, $$22, "wool");
        mb.a($$0, $$12, $$3, "bed");
        mb.a($$0, $$12, $$4, "carpet");
        mb.f($$0, (cml)cpo.iz, cpo.bP);
        mb.g($$0, cgc.rd, cpo.bP);
        mb.h($$0, cgc.uk, cpo.bP);
        mb.f($$0, (cml)cpo.iv, cpo.bL);
        mb.g($$0, cgc.qZ, cpo.bL);
        mb.h($$0, cgc.ug, cpo.bL);
        mb.f($$0, (cml)cpo.iw, cpo.bM);
        mb.g($$0, cgc.ra, cpo.bM);
        mb.h($$0, cgc.uh, cpo.bM);
        mb.f($$0, (cml)cpo.it, cpo.bJ);
        mb.g($$0, cgc.qX, cpo.bJ);
        mb.h($$0, cgc.ue, cpo.bJ);
        mb.f($$0, (cml)cpo.ir, cpo.bH);
        mb.g($$0, cgc.qV, cpo.bH);
        mb.h($$0, cgc.uc, cpo.bH);
        mb.f($$0, (cml)cpo.ix, cpo.bN);
        mb.g($$0, cgc.rb, cpo.bN);
        mb.h($$0, cgc.ui, cpo.bN);
        mb.f($$0, (cml)cpo.in, cpo.bD);
        mb.g($$0, cgc.qR, cpo.bD);
        mb.h($$0, cgc.tY, cpo.bD);
        mb.f($$0, (cml)cpo.is, cpo.bI);
        mb.g($$0, cgc.qW, cpo.bI);
        mb.h($$0, cgc.ud, cpo.bI);
        mb.f($$0, (cml)cpo.ip, cpo.bF);
        mb.g($$0, cgc.qT, cpo.bF);
        mb.h($$0, cgc.ua, cpo.bF);
        mb.f($$0, (cml)cpo.im, cpo.bC);
        mb.g($$0, cgc.qQ, cpo.bC);
        mb.h($$0, cgc.tX, cpo.bC);
        mb.f($$0, (cml)cpo.il, cpo.bB);
        mb.g($$0, cgc.qP, cpo.bB);
        mb.h($$0, cgc.tW, cpo.bB);
        mb.f($$0, (cml)cpo.iq, cpo.bG);
        mb.g($$0, cgc.qU, cpo.bG);
        mb.h($$0, cgc.ub, cpo.bG);
        mb.f($$0, (cml)cpo.iu, cpo.bK);
        mb.g($$0, cgc.qY, cpo.bK);
        mb.h($$0, cgc.uf, cpo.bK);
        mb.f($$0, (cml)cpo.iy, cpo.bO);
        mb.g($$0, cgc.rc, cpo.bO);
        mb.h($$0, cgc.uj, cpo.bO);
        mb.f($$0, (cml)cpo.ik, cpo.bA);
        mb.g($$0, cgc.qO, cpo.bA);
        mb.h($$0, cgc.tV, cpo.bA);
        mb.f($$0, (cml)cpo.io, cpo.bE);
        mb.g($$0, cgc.qS, cpo.bE);
        mb.h($$0, cgc.tZ, cpo.bE);
        mb.f($$0, (cml)cpo.rz, cpo.rB);
        mb.i($$0, cpo.ey, cgc.qJ);
        mb.j($$0, cpo.hO, cpo.ey);
        mb.k($$0, cpo.hO, cgc.qJ);
        mb.i($$0, cpo.eu, cgc.qF);
        mb.j($$0, cpo.hK, cpo.eu);
        mb.k($$0, cpo.hK, cgc.qF);
        mb.i($$0, cpo.ev, cgc.qG);
        mb.j($$0, cpo.hL, cpo.ev);
        mb.k($$0, cpo.hL, cgc.qG);
        mb.i($$0, cpo.es, cgc.qD);
        mb.j($$0, cpo.hI, cpo.es);
        mb.k($$0, cpo.hI, cgc.qD);
        mb.i($$0, cpo.eq, cgc.qB);
        mb.j($$0, cpo.hG, cpo.eq);
        mb.k($$0, cpo.hG, cgc.qB);
        mb.i($$0, cpo.ew, cgc.qH);
        mb.j($$0, cpo.hM, cpo.ew);
        mb.k($$0, cpo.hM, cgc.qH);
        mb.i($$0, cpo.em, cgc.qx);
        mb.j($$0, cpo.hC, cpo.em);
        mb.k($$0, cpo.hC, cgc.qx);
        mb.i($$0, cpo.er, cgc.qC);
        mb.j($$0, cpo.hH, cpo.er);
        mb.k($$0, cpo.hH, cgc.qC);
        mb.i($$0, cpo.eo, cgc.qz);
        mb.j($$0, cpo.hE, cpo.eo);
        mb.k($$0, cpo.hE, cgc.qz);
        mb.i($$0, cpo.el, cgc.qw);
        mb.j($$0, cpo.hB, cpo.el);
        mb.k($$0, cpo.hB, cgc.qw);
        mb.i($$0, cpo.ek, cgc.qv);
        mb.j($$0, cpo.hA, cpo.ek);
        mb.k($$0, cpo.hA, cgc.qv);
        mb.i($$0, cpo.ep, cgc.qA);
        mb.j($$0, cpo.hF, cpo.ep);
        mb.k($$0, cpo.hF, cgc.qA);
        mb.i($$0, cpo.et, cgc.qE);
        mb.j($$0, cpo.hJ, cpo.et);
        mb.k($$0, cpo.hJ, cgc.qE);
        mb.i($$0, cpo.ex, cgc.qI);
        mb.j($$0, cpo.hN, cpo.ex);
        mb.k($$0, cpo.hN, cgc.qI);
        mb.i($$0, cpo.ej, cgc.qu);
        mb.j($$0, cpo.hz, cpo.ej);
        mb.k($$0, cpo.hz, cgc.qu);
        mb.i($$0, cpo.en, cgc.qy);
        mb.j($$0, cpo.hD, cpo.en);
        mb.k($$0, cpo.hD, cgc.qy);
        mb.l($$0, cpo.hy, cgc.qJ);
        mb.l($$0, cpo.hu, cgc.qF);
        mb.l($$0, cpo.hv, cgc.qG);
        mb.l($$0, cpo.hs, cgc.qD);
        mb.l($$0, cpo.hq, cgc.qB);
        mb.l($$0, cpo.hw, cgc.qH);
        mb.l($$0, cpo.hm, cgc.qx);
        mb.l($$0, cpo.hr, cgc.qC);
        mb.l($$0, cpo.ho, cgc.qz);
        mb.l($$0, cpo.hl, cgc.qw);
        mb.l($$0, cpo.hk, cgc.qv);
        mb.l($$0, cpo.hp, cgc.qA);
        mb.l($$0, cpo.ht, cgc.qE);
        mb.l($$0, cpo.hx, cgc.qI);
        mb.l($$0, cpo.hj, cgc.qu);
        mb.l($$0, cpo.hn, cgc.qy);
        mb.m($$0, cpo.mb, cgc.qJ);
        mb.m($$0, cpo.lX, cgc.qF);
        mb.m($$0, cpo.lY, cgc.qG);
        mb.m($$0, cpo.lV, cgc.qD);
        mb.m($$0, cpo.lT, cgc.qB);
        mb.m($$0, cpo.lZ, cgc.qH);
        mb.m($$0, cpo.lP, cgc.qx);
        mb.m($$0, cpo.lU, cgc.qC);
        mb.m($$0, cpo.lR, cgc.qz);
        mb.m($$0, cpo.lO, cgc.qw);
        mb.m($$0, cpo.lN, cgc.qv);
        mb.m($$0, cpo.lS, cgc.qA);
        mb.m($$0, cpo.lW, cgc.qE);
        mb.m($$0, cpo.ma, cgc.qI);
        mb.m($$0, cpo.lM, cgc.qu);
        mb.m($$0, cpo.lQ, cgc.qy);
        ls.a(lq.b, cgc.vU).a(Character.valueOf('S'), cgc.oE).a(Character.valueOf('H'), cgc.vA).b("S").b("H").b("has_string", mb.a(cgc.oE)).b("has_honeycomb", mb.a(cgc.vA)).a($$0);
        mb.n($$0, cpo.qb, cgc.qJ);
        mb.n($$0, cpo.pX, cgc.qF);
        mb.n($$0, cpo.pY, cgc.qG);
        mb.n($$0, cpo.pV, cgc.qD);
        mb.n($$0, cpo.pT, cgc.qB);
        mb.n($$0, cpo.pZ, cgc.qH);
        mb.n($$0, cpo.pP, cgc.qx);
        mb.n($$0, cpo.pU, cgc.qC);
        mb.n($$0, cpo.pR, cgc.qz);
        mb.n($$0, cpo.pO, cgc.qw);
        mb.n($$0, cpo.pN, cgc.qv);
        mb.n($$0, cpo.pS, cgc.qA);
        mb.n($$0, cpo.pW, cgc.qE);
        mb.n($$0, cpo.qa, cgc.qI);
        mb.n($$0, cpo.pM, cgc.qu);
        mb.n($$0, cpo.pQ, cgc.qy);
        lt.a(lq.a, cpo.eM, 1).b(cpo.rH).b(cgc.oI).b("has_mud", mb.a((cml)cpo.rH)).a($$0);
        ls.a(lq.a, cpo.eN, 4).a(Character.valueOf('#'), cpo.eM).b("##").b("##").b("has_packed_mud", mb.a((cml)cpo.eM)).a($$0);
        lt.a(lq.a, cpo.ad, 1).b(cpo.rH).b(cgc.bo).b("has_mangrove_roots", mb.a((cml)cpo.ac)).a($$0);
        ls.a(lq.d, cpo.hh, 6).a(Character.valueOf('#'), cpo.dK).a(Character.valueOf('S'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("XSX").b("X#X").b("XSX").b("has_rail", mb.a((cml)cpo.cP)).a($$0);
        lt.a(lq.a, cpo.g, 2).b(cpo.e).b(cpo.m).b("has_stone", mb.a((cml)cpo.e)).a($$0);
        ls.a(lq.b, cpo.gS).a(Character.valueOf('I'), cpo.ci).a(Character.valueOf('i'), cgc.nQ).b("III").b(" i ").b("iii").b("has_iron_block", mb.a((cml)cpo.ci)).a($$0);
        ls.a(lq.b, cgc.tL).a(Character.valueOf('/'), cgc.oB).a(Character.valueOf('_'), cpo.jE).b("///").b(" / ").b("/_/").b("has_stone_slab", mb.a((cml)cpo.jE)).a($$0);
        ls.a(lq.f, cgc.nH, 4).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.pi).a(Character.valueOf('Y'), cgc.oF).b("X").b("#").b("Y").b("has_feather", mb.a(cgc.oF)).b("has_flint", mb.a(cgc.pi)).a($$0);
        ls.a(lq.b, cpo.nU, 1).a(Character.valueOf('P'), ane.b).a(Character.valueOf('S'), ane.j).b("PSP").b("P P").b("PSP").b("has_planks", mb.a(ane.b)).b("has_wood_slab", mb.a(ane.j)).a($$0);
        ls.a(lq.i, cpo.fO).a(Character.valueOf('S'), cgc.ty).a(Character.valueOf('G'), cpo.aQ).a(Character.valueOf('O'), cpo.co).b("GGG").b("GSG").b("OOO").b("has_nether_star", mb.a(cgc.ty)).a($$0);
        ls.a(lq.b, cpo.pf).a(Character.valueOf('P'), ane.b).a(Character.valueOf('H'), cgc.vA).b("PPP").b("HHH").b("PPP").b("has_honeycomb", mb.a(cgc.vA)).a($$0);
        lt.a(lq.g, cgc.us).b(cgc.oC).a(cgc.uq, 6).b("has_beetroot", mb.a(cgc.uq)).a($$0);
        lt.a(lq.i, cgc.qJ).b(cgc.qr).b("black_dye").b("has_ink_sac", mb.a(cgc.qr)).a($$0);
        mb.a($$0, (cml)cgc.qJ, (cml)cpo.cd, "black_dye");
        lt.a(lq.h, cgc.rz, 2).b(cgc.rr).b("has_blaze_rod", mb.a(cgc.rr)).a($$0);
        lt.a(lq.i, cgc.qF).b(cgc.nM).b("blue_dye").b("has_lapis_lazuli", mb.a(cgc.nM)).a($$0);
        mb.a($$0, (cml)cgc.qF, (cml)cpo.cc, "blue_dye");
        mb.b($$0, lq.a, cpo.mW, cpo.iC);
        lt.a(lq.i, cgc.qK, 3).b(cgc.qL).b("bonemeal").b("has_bone", mb.a(cgc.qL)).a($$0);
        mb.b($$0, lq.i, cgc.qK, lq.a, cgc.iE, "bone_meal_from_bone_block", "bonemeal");
        lt.a(lq.i, cgc.qb).a(cgc.qa, 3).b(cgc.pP).b("has_paper", mb.a(cgc.qa)).a($$0);
        ls.a(lq.a, cpo.cl).a(Character.valueOf('#'), ane.b).a(Character.valueOf('X'), cgc.qb).b("###").b("XXX").b("###").b("has_book", mb.a(cgc.qb)).a($$0);
        ls.a(lq.f, cgc.nG).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.oE).b(" #X").b("# X").b(" #X").b("has_string", mb.a(cgc.oE)).a($$0);
        ls.a(lq.i, cgc.oC, 4).a(Character.valueOf('#'), ane.b).b("# #").b(" # ").b("has_brown_mushroom", mb.a((cml)cpo.cf)).b("has_red_mushroom", mb.a((cml)cpo.cg)).b("has_mushroom_stew", mb.a(cgc.oD)).a($$0);
        ls.a(lq.g, cgc.oJ).a(Character.valueOf('#'), cgc.oI).b("###").b("has_wheat", mb.a(cgc.oI)).a($$0);
        ls.a(lq.h, cpo.fs).a(Character.valueOf('B'), cgc.rr).a(Character.valueOf('#'), ane.ay).b(" B ").b("###").b("has_blaze_rod", mb.a(cgc.rr)).a($$0);
        ls.a(lq.a, cpo.cj).a(Character.valueOf('#'), cgc.pX).b("##").b("##").b("has_brick", mb.a(cgc.pX)).a($$0);
        lt.a(lq.i, cgc.qG).b(cgc.qt).b("brown_dye").b("has_cocoa_beans", mb.a(cgc.qt)).a($$0);
        ls.a(lq.i, cgc.pK).a(Character.valueOf('#'), cgc.nQ).b("# #").b(" # ").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.g, cpo.eh).a(Character.valueOf('A'), cgc.pQ).a(Character.valueOf('B'), cgc.qM).a(Character.valueOf('C'), cgc.oI).a(Character.valueOf('E'), cgc.qd).b("AAA").b("BEB").b("CCC").b("has_egg", mb.a(cgc.qd)).a($$0);
        ls.a(lq.b, cpo.og).a(Character.valueOf('L'), ane.r).a(Character.valueOf('S'), cgc.oB).a(Character.valueOf('C'), ane.as).b(" S ").b("SCS").b("LLL").b("has_stick", mb.a(cgc.oB)).b("has_coal", mb.a(ane.as)).a($$0);
        ls.a(lq.d, cgc.nf).a(Character.valueOf('#'), cgc.qh).a(Character.valueOf('X'), cgc.tl).b("# ").b(" X").b("has_carrot", mb.a(cgc.tl)).a($$0);
        ls.a(lq.d, cgc.ng).a(Character.valueOf('#'), cgc.qh).a(Character.valueOf('X'), cgc.dh).b("# ").b(" X").b("has_warped_fungus", mb.a(cgc.dh)).a($$0);
        ls.a(lq.h, cpo.ft).a(Character.valueOf('#'), cgc.nQ).b("# #").b("# #").b("###").b("has_water_bucket", mb.a(cgc.pL)).a($$0);
        ls.a(lq.b, cpo.pc).a(Character.valueOf('#'), ane.j).b("# #").b("# #").b("###").b("has_wood_slab", mb.a(ane.j)).a($$0);
        ls.a(lq.b, cpo.cv).a(Character.valueOf('#'), ane.b).b("###").b("# #").b("###").b("has_lots_of_items", new bx.a(ba.a, cj.d.b(10), cj.d.e, cj.d.e, new bz[0])).a($$0);
        lt.a(lq.d, cgc.nb).b(cpo.cv).b(cgc.na).b("has_minecart", mb.a(cgc.na)).a($$0);
        mb.c($$0, (cml)cgc.nr, cgc.nq);
        mb.c($$0, (cml)cgc.nn, cgc.nm);
        mb.c($$0, (cml)cgc.nv, cgc.nu);
        mb.c($$0, (cml)cgc.np, cgc.no);
        mb.c($$0, (cml)cgc.nj, cgc.ni);
        mb.c($$0, (cml)cgc.nl, cgc.nk);
        mb.c($$0, (cml)cgc.nx, cgc.nw);
        mb.b(lq.a, (cml)cpo.he, ciz.a(cpo.jN)).b("has_chiseled_quartz_block", mb.a((cml)cpo.he)).b("has_quartz_block", mb.a((cml)cpo.hd)).b("has_quartz_pillar", mb.a((cml)cpo.hf)).a($$0);
        mb.b(lq.a, (cml)cpo.eL, ciz.a(cpo.jK)).b("has_tag", mb.a(ane.c)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.dR, (cml)cgc.pY);
        ls.a(lq.e, cgc.qi).a(Character.valueOf('#'), cgc.nU).a(Character.valueOf('X'), cgc.ll).b(" # ").b("#X#").b(" # ").b("has_redstone", mb.a(cgc.ll)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.nI, lq.a, cgc.aq);
        ls.a(lq.a, cpo.k, 4).a(Character.valueOf('D'), cpo.j).a(Character.valueOf('G'), cpo.L).b("DG").b("GD").b("has_gravel", mb.a((cml)cpo.L)).a($$0);
        ls.a(lq.c, cpo.gY).a(Character.valueOf('#'), cpo.dK).a(Character.valueOf('X'), cgc.nN).a(Character.valueOf('I'), cpo.b).b(" # ").b("#X#").b("III").b("has_quartz", mb.a(cgc.nN)).a($$0);
        ls.a(lq.e, cgc.qe).a(Character.valueOf('#'), cgc.nQ).a(Character.valueOf('X'), cgc.ll).b(" # ").b("#X#").b(" # ").b("has_redstone", mb.a(cgc.ll)).a($$0);
        ls.a(lq.g, cgc.re, 8).a(Character.valueOf('#'), cgc.oI).a(Character.valueOf('X'), cgc.qt).b("#X#").b("has_cocoa", mb.a(cgc.qt)).a($$0);
        ls.a(lq.b, cpo.cA).a(Character.valueOf('#'), ane.b).b("##").b("##").b("unlock_right_away", cq.a.f()).a(false).a($$0);
        ls.a(lq.f, cgc.uZ).a(Character.valueOf('~'), cgc.oE).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('&'), cgc.nQ).a(Character.valueOf('$'), cpo.fH).b("#&#").b("~$~").b(" # ").b("has_string", mb.a(cgc.oE)).b("has_iron_ingot", mb.a(cgc.nQ)).b("has_tripwire_hook", mb.a((cml)cpo.fH)).a($$0);
        ls.a(lq.b, cpo.nT).a(Character.valueOf('#'), ane.b).a(Character.valueOf('@'), cgc.oE).b("@@").b("##").b("has_string", mb.a(cgc.oE)).a($$0);
        mb.b(lq.a, (cml)cpo.jq, ciz.a(cpo.jO)).b("has_red_sandstone", mb.a((cml)cpo.jp)).b("has_chiseled_red_sandstone", mb.a((cml)cpo.jq)).b("has_cut_red_sandstone", mb.a((cml)cpo.jr)).a($$0);
        mb.g($$0, lq.a, cpo.aW, cpo.jF);
        mb.b($$0, lq.i, cgc.nS, lq.a, cgc.ax, mb.d(cgc.nS), mb.c(cgc.nS));
        lt.a(lq.i, cgc.nS, 9).b(cpo.rb).b(mb.c(cgc.nS)).b(mb.b(cpo.rb), mb.a((cml)cpo.rb)).a($$0, mb.a((cml)cgc.nS, (cml)cpo.rb));
        mb.b($$0);
        lt.a(lq.i, cgc.qD, 2).b(cgc.qF).b(cgc.qH).b("cyan_dye").b("has_green_dye", mb.a(cgc.qH)).b("has_blue_dye", mb.a(cgc.qF)).a($$0);
        ls.a(lq.a, cpo.ib).a(Character.valueOf('S'), cgc.tE).a(Character.valueOf('I'), cgc.qJ).b("SSS").b("SIS").b("SSS").b("has_prismarine_shard", mb.a(cgc.tE)).a($$0);
        ls.a(lq.c, cpo.gZ).a(Character.valueOf('Q'), cgc.nN).a(Character.valueOf('G'), cpo.aQ).a(Character.valueOf('W'), ciz.a(ane.j)).b("GGG").b("QQQ").b("WWW").b("has_quartz", mb.a(cgc.nN)).a($$0);
        ls.a(lq.a, cpo.rV, 4).a(Character.valueOf('S'), cpo.rN).b("SS").b("SS").b("has_polished_deepslate", mb.a((cml)cpo.rN)).a($$0);
        ls.a(lq.a, cpo.rR, 4).a(Character.valueOf('S'), cpo.rV).b("SS").b("SS").b("has_deepslate_bricks", mb.a((cml)cpo.rV)).a($$0);
        ls.a(lq.d, cpo.bq, 6).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cpo.dx).a(Character.valueOf('X'), cgc.nQ).b("X X").b("X#X").b("XRX").b("has_rail", mb.a((cml)cpo.cP)).a($$0);
        ls.a(lq.e, cgc.ou).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nK).b("XX").b("X#").b(" #").b("has_diamond", mb.a(cgc.nK)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.nK, lq.a, cgc.az);
        ls.a(lq.f, cgc.oZ).a(Character.valueOf('X'), cgc.nK).b("X X").b("X X").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.f, cgc.oX).a(Character.valueOf('X'), cgc.nK).b("X X").b("XXX").b("XXX").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.f, cgc.oW).a(Character.valueOf('X'), cgc.nK).b("XXX").b("X X").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.e, cgc.ov).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nK).b("XX").b(" #").b(" #").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.f, cgc.oY).a(Character.valueOf('X'), cgc.nK).b("XXX").b("X X").b("X X").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.e, cgc.ot).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nK).b("XXX").b(" # ").b(" # ").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.e, cgc.os).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nK).b("X").b("#").b("#").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.f, cgc.or).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nK).b("X").b("X").b("#").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.a, cpo.e, 2).a(Character.valueOf('Q'), cgc.nN).a(Character.valueOf('C'), cpo.m).b("CQ").b("QC").b("has_quartz", mb.a(cgc.nN)).a($$0);
        ls.a(lq.c, cpo.aU).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cpo.m).a(Character.valueOf('X'), cgc.nG).b("###").b("#X#").b("#R#").b("has_bow", mb.a(cgc.nG)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.rt, (cml)cgc.wp);
        ls.a(lq.c, cpo.hi).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cpo.m).b("###").b("# #").b("#R#").b("has_redstone", mb.a(cgc.ll)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.nL, lq.a, cgc.fW);
        ls.a(lq.b, cpo.fr).a(Character.valueOf('B'), cgc.qb).a(Character.valueOf('#'), cpo.co).a(Character.valueOf('D'), cgc.nK).b(" B ").b("D#D").b("###").b("has_obsidian", mb.a((cml)cpo.co)).a($$0);
        ls.a(lq.b, cpo.fG).a(Character.valueOf('#'), cpo.co).a(Character.valueOf('E'), cgc.rD).b("###").b("#E#").b("###").b("has_ender_eye", mb.a(cgc.rD)).a($$0);
        lt.a(lq.i, cgc.rD).b(cgc.rq).b(cgc.rz).b("has_blaze_powder", mb.a(cgc.rz)).a($$0);
        ls.a(lq.a, cpo.kz, 4).a(Character.valueOf('#'), cpo.fz).b("##").b("##").b("has_end_stone", mb.a((cml)cpo.fz)).a($$0);
        ls.a(lq.b, cgc.ul).a(Character.valueOf('T'), cgc.rs).a(Character.valueOf('E'), cgc.rD).a(Character.valueOf('G'), cpo.aQ).b("GGG").b("GEG").b("GTG").b("has_ender_eye", mb.a(cgc.rD)).a($$0);
        ls.a(lq.b, cpo.kt, 4).a(Character.valueOf('#'), cgc.un).a(Character.valueOf('/'), cgc.rr).b("/").b("#").b("has_chorus_fruit_popped", mb.a(cgc.un)).a($$0);
        lt.a(lq.h, cgc.ry).b(cgc.rx).b(cpo.cf).b(cgc.qM).b("has_spider_eye", mb.a(cgc.rx)).a($$0);
        lt.a(lq.i, cgc.tf, 3).b(cgc.oG).b(cgc.rz).a(ciz.a(cgc.nI, cgc.nJ)).b("has_blaze_powder", mb.a(cgc.rz)).a($$0);
        lt.a(lq.i, cgc.tA, 3).b(cgc.oG).b(cgc.qa).b("has_gunpowder", mb.a(cgc.oG)).a($$0, "firework_rocket_simple");
        ls.a(lq.e, cgc.qh).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.oE).b("  #").b(" #X").b("# X").b("has_string", mb.a(cgc.oE)).a($$0);
        lt.a(lq.e, cgc.nE).b(cgc.nQ).b(cgc.pi).b("has_flint", mb.a(cgc.pi)).b("has_obsidian", mb.a((cml)cpo.co)).a($$0);
        ls.a(lq.b, cpo.fR).a(Character.valueOf('#'), cgc.pX).b("# #").b(" # ").b("has_brick", mb.a(cgc.pX)).a($$0);
        ls.a(lq.b, cpo.cD).a(Character.valueOf('#'), ane.ay).b("###").b("# #").b("###").b("has_cobblestone", mb.a(ane.ay)).a($$0);
        lt.a(lq.d, cgc.nc).b(cpo.cD).b(cgc.na).b("has_minecart", mb.a(cgc.na)).a($$0);
        ls.a(lq.h, cgc.rw, 3).a(Character.valueOf('#'), cpo.aQ).b("# #").b(" # ").b("has_glass", mb.a((cml)cpo.aQ)).a($$0);
        ls.a(lq.b, cpo.eZ, 16).a(Character.valueOf('#'), cpo.aQ).b("###").b("###").b("has_glass", mb.a((cml)cpo.aQ)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.ed, (cml)cgc.qk);
        lt.a(lq.b, cgc.tj).b(cgc.ti).b(cgc.qs).b("has_item_frame", mb.a(cgc.ti)).b("has_glow_ink_sac", mb.a(cgc.qs)).a($$0);
        ls.a(lq.g, cgc.pm).a(Character.valueOf('#'), cgc.nU).a(Character.valueOf('X'), cgc.nF).b("###").b("#X#").b("###").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.e, cgc.ok).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("XX").b("X#").b(" #").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.f, cgc.pd).a(Character.valueOf('X'), cgc.nU).b("X X").b("X X").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.h, cgc.tq).a(Character.valueOf('#'), cgc.rt).a(Character.valueOf('X'), cgc.tl).b("###").b("#X#").b("###").b("has_gold_nugget", mb.a(cgc.rt)).a($$0);
        ls.a(lq.f, cgc.pb).a(Character.valueOf('X'), cgc.nU).b("X X").b("XXX").b("XXX").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.f, cgc.pa).a(Character.valueOf('X'), cgc.nU).b("XXX").b("X X").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.e, cgc.ol).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("XX").b(" #").b(" #").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.f, cgc.pc).a(Character.valueOf('X'), cgc.nU).b("XXX").b("X X").b("X X").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.e, cgc.oj).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("XXX").b(" # ").b(" # ").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.d, cpo.bp, 6).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("X X").b("X#X").b("XRX").b("has_rail", mb.a((cml)cpo.cP)).a($$0);
        ls.a(lq.e, cgc.oi).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("X").b("#").b("#").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        ls.a(lq.f, cgc.oh).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nU).b("X").b("X").b("#").b("has_gold_ingot", mb.a(cgc.nU)).a($$0);
        mb.b($$0, lq.i, cgc.nU, lq.a, cgc.ay, "gold_ingot_from_gold_block", "gold_ingot");
        mb.a($$0, lq.i, cgc.rt, lq.i, (cml)cgc.nU, "gold_ingot_from_nuggets", "gold_ingot");
        lt.a(lq.a, cpo.c).b(cpo.e).b(cgc.nN).b("has_quartz", mb.a(cgc.nN)).a($$0);
        lt.a(lq.i, cgc.qB, 2).b(cgc.qJ).b(cgc.qu).b("has_white_dye", mb.a(cgc.qu)).b("has_black_dye", mb.a(cgc.qJ)).a($$0);
        mb.b($$0, lq.a, cpo.ij, cgc.oI);
        mb.d($$0, (cml)cpo.gX, cgc.nQ);
        lt.a(lq.g, cgc.vD, 4).b(cgc.lt).a(cgc.rw, 4).b("has_honey_block", mb.a((cml)cpo.pg)).a($$0);
        mb.a($$0, lq.c, (cml)cpo.pg, (cml)cgc.vD);
        mb.a($$0, lq.b, (cml)cpo.ph, (cml)cgc.vA);
        ls.a(lq.c, cpo.hc).a(Character.valueOf('C'), cpo.cv).a(Character.valueOf('I'), cgc.nQ).b("I I").b("ICI").b(" I ").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        lt.a(lq.d, cgc.ne).b(cpo.hc).b(cgc.na).b("has_minecart", mb.a(cgc.na)).a($$0);
        ls.a(lq.e, cgc.op).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("XX").b("X#").b(" #").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.b, cpo.eX, 16).a(Character.valueOf('#'), cgc.nQ).b("###").b("###").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.f, cgc.oV).a(Character.valueOf('X'), cgc.nQ).b("X X").b("X X").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.f, cgc.oT).a(Character.valueOf('X'), cgc.nQ).b("X X").b("XXX").b("XXX").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        mb.a((cml)cpo.dy, ciz.a(cgc.nQ)).a(mb.b(cgc.nQ), mb.a(cgc.nQ)).a($$0);
        ls.a(lq.f, cgc.oS).a(Character.valueOf('X'), cgc.nQ).b("XXX").b("X X").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.e, cgc.oq).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("XX").b(" #").b(" #").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        mb.b($$0, lq.i, cgc.nQ, lq.a, cgc.aw, "iron_ingot_from_iron_block", "iron_ingot");
        mb.a($$0, lq.i, cgc.uB, lq.i, (cml)cgc.nQ, "iron_ingot_from_nuggets", "iron_ingot");
        ls.a(lq.f, cgc.oU).a(Character.valueOf('X'), cgc.nQ).b("XXX").b("X X").b("X X").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.e, cgc.oo).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("XXX").b(" # ").b(" # ").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.e, cgc.on).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("X").b("#").b("#").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.f, cgc.om).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("X").b("X").b("#").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        mb.a($$0, lq.c, (cml)cpo.hY, (cml)cgc.nQ);
        ls.a(lq.b, cgc.ti).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.pP).b("###").b("#X#").b("###").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.b, cpo.dT).a(Character.valueOf('#'), ane.b).a(Character.valueOf('X'), cgc.nK).b("###").b("#X#").b("###").b("has_diamond", mb.a(cgc.nK)).a($$0);
        ls.a(lq.b, cpo.cO, 3).a(Character.valueOf('#'), cgc.oB).b("# #").b("###").b("# #").b("has_stick", mb.a(cgc.oB)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.nM, lq.a, cgc.cm);
        ls.a(lq.e, cgc.tQ, 2).a(Character.valueOf('~'), cgc.oE).a(Character.valueOf('O'), cgc.qc).b("~~ ").b("~O ").b("  ~").b("has_slime_ball", mb.a(cgc.qc)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.pP, (cml)cgc.tK);
        ls.a(lq.f, cgc.oN).a(Character.valueOf('X'), cgc.pP).b("X X").b("X X").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.f, cgc.oL).a(Character.valueOf('X'), cgc.pP).b("X X").b("XXX").b("XXX").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.f, cgc.oK).a(Character.valueOf('X'), cgc.pP).b("XXX").b("X X").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.f, cgc.oM).a(Character.valueOf('X'), cgc.pP).b("XXX").b("X X").b("X X").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.i, cgc.tP).a(Character.valueOf('X'), cgc.pP).b("X X").b("XXX").b("X X").b("has_leather", mb.a(cgc.pP)).a($$0);
        ls.a(lq.c, cpo.oa).a(Character.valueOf('S'), ane.j).a(Character.valueOf('B'), cpo.cl).b("SSS").b(" B ").b(" S ").b("has_book", mb.a(cgc.qb)).a($$0);
        ls.a(lq.c, cpo.dw).a(Character.valueOf('#'), cpo.m).a(Character.valueOf('X'), cgc.oB).b("X").b("#").b("has_cobblestone", mb.a((cml)cpo.m)).a($$0);
        mb.a($$0, (cml)cgc.qx, (cml)cpo.bU, "light_blue_dye");
        lt.a(lq.i, cgc.qx, 2).b(cgc.qF).b(cgc.qu).b("light_blue_dye").b("has_blue_dye", mb.a(cgc.qF)).b("has_white_dye", mb.a(cgc.qu)).a($$0, "light_blue_dye_from_blue_white_dye");
        mb.a($$0, (cml)cgc.qC, (cml)cpo.bW, "light_gray_dye");
        lt.a(lq.i, cgc.qC, 2).b(cgc.qB).b(cgc.qu).b("light_gray_dye").b("has_gray_dye", mb.a(cgc.qB)).b("has_white_dye", mb.a(cgc.qu)).a($$0, "light_gray_dye_from_gray_white_dye");
        lt.a(lq.i, cgc.qC, 3).b(cgc.qJ).a(cgc.qu, 2).b("light_gray_dye").b("has_white_dye", mb.a(cgc.qu)).b("has_black_dye", mb.a(cgc.qJ)).a($$0, "light_gray_dye_from_black_white_dye");
        mb.a($$0, (cml)cgc.qC, (cml)cpo.cb, "light_gray_dye");
        mb.a($$0, (cml)cgc.qC, (cml)cpo.bZ, "light_gray_dye");
        mb.d($$0, (cml)cpo.gW, cgc.nU);
        ls.a(lq.c, cpo.rr).a(Character.valueOf('#'), cgc.nS).b("#").b("#").b("#").b("has_copper_ingot", mb.a(cgc.nS)).a($$0);
        lt.a(lq.i, cgc.qz, 2).b(cgc.qH).b(cgc.qu).b("has_green_dye", mb.a(cgc.qH)).b("has_white_dye", mb.a(cgc.qu)).a($$0);
        ls.a(lq.a, cpo.eg).a(Character.valueOf('A'), cpo.ef).a(Character.valueOf('B'), cpo.cp).b("A").b("B").b("has_carved_pumpkin", mb.a((cml)cpo.ef)).a($$0);
        mb.a($$0, (cml)cgc.qw, (cml)cpo.bV, "magenta_dye");
        lt.a(lq.i, cgc.qw, 4).b(cgc.qF).a(cgc.qI, 2).b(cgc.qu).b("magenta_dye").b("has_blue_dye", mb.a(cgc.qF)).b("has_rose_red", mb.a(cgc.qI)).b("has_white_dye", mb.a(cgc.qu)).a($$0, "magenta_dye_from_blue_red_white_dye");
        lt.a(lq.i, cgc.qw, 3).b(cgc.qF).b(cgc.qI).b(cgc.qA).b("magenta_dye").b("has_pink_dye", mb.a(cgc.qA)).b("has_blue_dye", mb.a(cgc.qF)).b("has_red_dye", mb.a(cgc.qI)).a($$0, "magenta_dye_from_blue_red_pink");
        mb.a($$0, cgc.qw, (cml)cpo.iE, "magenta_dye", 2);
        lt.a(lq.i, cgc.qw, 2).b(cgc.qE).b(cgc.qA).b("magenta_dye").b("has_pink_dye", mb.a(cgc.qA)).b("has_purple_dye", mb.a(cgc.qE)).a($$0, "magenta_dye_from_purple_and_pink");
        mb.a($$0, lq.a, (cml)cpo.kJ, (cml)cgc.rA);
        lt.a(lq.h, cgc.rA).b(cgc.rz).b(cgc.qc).b("has_blaze_powder", mb.a(cgc.rz)).a($$0);
        ls.a(lq.i, cgc.tp).a(Character.valueOf('#'), cgc.qa).a(Character.valueOf('X'), cgc.qe).b("###").b("#X#").b("###").b("has_compass", mb.a(cgc.qe)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.fa, (cml)cgc.rh, "has_melon");
        lt.a(lq.i, cgc.rk).b(cgc.rh).b("has_melon", mb.a(cgc.rh)).a($$0);
        ls.a(lq.d, cgc.na).a(Character.valueOf('#'), cgc.nQ).b("# #").b("###").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        lt.a(lq.a, cpo.cn).b(cpo.m).b(cpo.ff).b("mossy_cobblestone").b("has_vine", mb.a((cml)cpo.ff)).a($$0, mb.a((cml)cpo.cn, (cml)cpo.ff));
        lt.a(lq.a, cpo.eJ).b(cpo.eI).b(cpo.ff).b("mossy_stone_bricks").b("has_vine", mb.a((cml)cpo.ff)).a($$0, mb.a((cml)cpo.eJ, (cml)cpo.ff));
        lt.a(lq.a, cpo.cn).b(cpo.m).b(cpo.rB).b("mossy_cobblestone").b("has_moss_block", mb.a((cml)cpo.rB)).a($$0, mb.a((cml)cpo.cn, (cml)cpo.rB));
        lt.a(lq.a, cpo.eJ).b(cpo.eI).b(cpo.rB).b("mossy_stone_bricks").b("has_moss_block", mb.a((cml)cpo.rB)).a($$0, mb.a((cml)cpo.eJ, (cml)cpo.rB));
        lt.a(lq.g, cgc.oD).b(cpo.cf).b(cpo.cg).b(cgc.oC).b("has_mushroom_stew", mb.a(cgc.oD)).b("has_bowl", mb.a(cgc.oC)).b("has_brown_mushroom", mb.a((cml)cpo.cf)).b("has_red_mushroom", mb.a((cml)cpo.cg)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.fn, (cml)cgc.tD);
        mb.b($$0, lq.a, cpo.kK, cgc.ru);
        ls.a(lq.c, cpo.aY).a(Character.valueOf('#'), ane.b).a(Character.valueOf('X'), cgc.ll).b("###").b("#X#").b("###").b("has_redstone", mb.a(cgc.ll)).a($$0);
        ls.a(lq.c, cpo.kO).a(Character.valueOf('Q'), cgc.nN).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cpo.m).b("###").b("RRQ").b("###").b("has_quartz", mb.a(cgc.nN)).a($$0);
        mb.a($$0, (cml)cgc.qv, (cml)cpo.bY, "orange_dye");
        lt.a(lq.i, cgc.qv, 2).b(cgc.qI).b(cgc.qy).b("orange_dye").b("has_red_dye", mb.a(cgc.qI)).b("has_yellow_dye", mb.a(cgc.qy)).a($$0, "orange_dye_from_red_yellow");
        ls.a(lq.b, cgc.pl).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ciz.a(ane.a)).b("###").b("#X#").b("###").b("has_wool", mb.a(ane.a)).a($$0);
        ls.a(lq.i, cgc.qa, 3).a(Character.valueOf('#'), cpo.dS).b("###").b("has_reeds", mb.a((cml)cpo.dS)).a($$0);
        ls.a(lq.a, cpo.hf, 2).a(Character.valueOf('#'), cpo.hd).b("#").b("#").b("has_chiseled_quartz_block", mb.a((cml)cpo.he)).b("has_quartz_block", mb.a((cml)cpo.hd)).b("has_quartz_pillar", mb.a((cml)cpo.hf)).a($$0);
        mb.b($$0, lq.a, cpo.iC, cpo.dO);
        mb.a($$0, cgc.qA, (cml)cpo.iG, "pink_dye", 2);
        mb.a($$0, (cml)cgc.qA, (cml)cpo.ca, "pink_dye");
        lt.a(lq.i, cgc.qA, 2).b(cgc.qI).b(cgc.qu).b("pink_dye").b("has_white_dye", mb.a(cgc.qu)).b("has_red_dye", mb.a(cgc.qI)).a($$0, "pink_dye_from_red_white_dye");
        ls.a(lq.c, cpo.by).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('#'), cpo.m).a(Character.valueOf('T'), ane.b).a(Character.valueOf('X'), cgc.nQ).b("TTT").b("#X#").b("#R#").b("has_redstone", mb.a(cgc.ll)).a($$0);
        mb.e($$0, lq.a, cpo.ea, cpo.dZ);
        mb.a($$0, lq.a, (cml)cpo.hZ, (cml)cgc.tE);
        mb.b($$0, lq.a, cpo.ia, cgc.tE);
        lt.a(lq.g, cgc.tz).b(cpo.dV).b(cgc.qM).b(cgc.qd).b("has_carved_pumpkin", mb.a((cml)cpo.ef)).b("has_pumpkin", mb.a((cml)cpo.dV)).a($$0);
        lt.a(lq.i, cgc.rj, 4).b(cpo.dV).b("has_pumpkin", mb.a((cml)cpo.dV)).a($$0);
        lt.a(lq.i, cgc.qE, 2).b(cgc.qF).b(cgc.qI).b("has_blue_dye", mb.a(cgc.qF)).b("has_red_dye", mb.a(cgc.qI)).a($$0);
        ls.a(lq.b, cpo.kP).a(Character.valueOf('#'), cpo.cv).a(Character.valueOf('-'), cgc.uA).b("-").b("#").b("-").b("has_shulker_shell", mb.a(cgc.uA)).a($$0);
        ls.a(lq.a, cpo.kw, 4).a(Character.valueOf('F'), cgc.un).b("FF").b("FF").b("has_chorus_fruit_popped", mb.a(cgc.un)).a($$0);
        ls.a(lq.a, cpo.kx).a(Character.valueOf('#'), cpo.jQ).b("#").b("#").b("has_purpur_block", mb.a((cml)cpo.kw)).a($$0);
        mb.a(lq.a, (cml)cpo.jQ, ciz.a(cpo.kw, cpo.kx)).a("has_purpur_block", mb.a((cml)cpo.kw)).a($$0);
        mb.b((cml)cpo.ky, ciz.a(cpo.kw, cpo.kx)).a("has_purpur_block", mb.a((cml)cpo.kw)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.hd, (cml)cgc.nN);
        ls.a(lq.a, cpo.pK, 4).a(Character.valueOf('#'), cpo.hd).b("##").b("##").b("has_quartz_block", mb.a((cml)cpo.hd)).a($$0);
        mb.a(lq.a, (cml)cpo.jN, ciz.a(cpo.he, cpo.hd, cpo.hf)).a("has_chiseled_quartz_block", mb.a((cml)cpo.he)).a("has_quartz_block", mb.a((cml)cpo.hd)).a("has_quartz_pillar", mb.a((cml)cpo.hf)).a($$0);
        mb.b((cml)cpo.hg, ciz.a(cpo.he, cpo.hd, cpo.hf)).a("has_chiseled_quartz_block", mb.a((cml)cpo.he)).a("has_quartz_block", mb.a((cml)cpo.hd)).a("has_quartz_pillar", mb.a((cml)cpo.hf)).a($$0);
        lt.a(lq.g, cgc.tI).b(cgc.tn).b(cgc.tH).b(cgc.oC).b(cgc.tl).b(cpo.cf).b("rabbit_stew").b("has_cooked_rabbit", mb.a(cgc.tH)).a($$0, mb.a((cml)cgc.tI, (cml)cgc.de));
        lt.a(lq.g, cgc.tI).b(cgc.tn).b(cgc.tH).b(cgc.oC).b(cgc.tl).b(cpo.cg).b("rabbit_stew").b("has_cooked_rabbit", mb.a(cgc.tH)).a($$0, mb.a((cml)cgc.tI, (cml)cgc.df));
        ls.a(lq.d, cpo.cP, 16).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.nQ).b("X X").b("X#X").b("X X").b("has_minecart", mb.a(cgc.na)).a($$0);
        mb.a($$0, lq.c, (cml)cgc.ll, lq.c, cgc.ln);
        ls.a(lq.c, cpo.fB).a(Character.valueOf('R'), cgc.ll).a(Character.valueOf('G'), cpo.ed).b(" R ").b("RGR").b(" R ").b("has_glowstone", mb.a((cml)cpo.ed)).a($$0);
        ls.a(lq.c, cpo.dK).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), cgc.ll).b("X").b("#").b("has_redstone", mb.a(cgc.ll)).a($$0);
        mb.a($$0, (cml)cgc.qI, (cml)cgc.uq, "red_dye");
        mb.a($$0, (cml)cgc.qI, (cml)cpo.bT, "red_dye");
        mb.a($$0, cgc.qI, (cml)cpo.iF, "red_dye", 2);
        lt.a(lq.i, cgc.qI).b(cpo.bX).b("red_dye").b("has_red_flower", mb.a((cml)cpo.bX)).a($$0, "red_dye_from_tulip");
        ls.a(lq.a, cpo.kL).a(Character.valueOf('W'), cgc.ru).a(Character.valueOf('N'), cgc.tD).b("NW").b("WN").b("has_nether_wart", mb.a(cgc.ru)).a($$0);
        ls.a(lq.a, cpo.jp).a(Character.valueOf('#'), cpo.K).b("##").b("##").b("has_sand", mb.a((cml)cpo.K)).a($$0);
        mb.a(lq.a, (cml)cpo.jO, ciz.a(cpo.jp, cpo.jq)).a("has_red_sandstone", mb.a((cml)cpo.jp)).a("has_chiseled_red_sandstone", mb.a((cml)cpo.jq)).a($$0);
        mb.b((cml)cpo.js, ciz.a(cpo.jp, cpo.jq, cpo.jr)).a("has_red_sandstone", mb.a((cml)cpo.jp)).a("has_chiseled_red_sandstone", mb.a((cml)cpo.jq)).a("has_cut_red_sandstone", mb.a((cml)cpo.jr)).a($$0);
        ls.a(lq.c, cpo.ei).a(Character.valueOf('#'), cpo.dK).a(Character.valueOf('X'), cgc.ll).a(Character.valueOf('I'), cpo.b).b("#X#").b("III").b("has_redstone_torch", mb.a((cml)cpo.dK)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.aV, (cml)cpo.I);
        mb.a(lq.a, (cml)cpo.jF, ciz.a(cpo.aV, cpo.aW)).a("has_sandstone", mb.a((cml)cpo.aV)).a("has_chiseled_sandstone", mb.a((cml)cpo.aW)).a($$0);
        mb.b((cml)cpo.fD, ciz.a(cpo.aV, cpo.aW, cpo.aX)).a("has_sandstone", mb.a((cml)cpo.aV)).a("has_chiseled_sandstone", mb.a((cml)cpo.aW)).a("has_cut_sandstone", mb.a((cml)cpo.aX)).a($$0);
        ls.a(lq.a, cpo.ii).a(Character.valueOf('S'), cgc.tE).a(Character.valueOf('C'), cgc.tF).b("SCS").b("CCC").b("SCS").b("has_prismarine_crystals", mb.a(cgc.tF)).a($$0);
        ls.a(lq.e, cgc.rg).a(Character.valueOf('#'), cgc.nQ).b(" #").b("# ").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.f, cgc.uy).a(Character.valueOf('W'), ane.b).a(Character.valueOf('o'), cgc.nQ).b("WoW").b("WWW").b(" W ").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        mb.a($$0, lq.i, (cml)cgc.qc, lq.c, cgc.ls);
        mb.f($$0, lq.a, cpo.jr, cpo.jp);
        mb.f($$0, lq.a, cpo.aX, cpo.aV);
        mb.a($$0, lq.a, (cml)cpo.dP, (cml)cgc.pO);
        ls.a(lq.b, cpo.dN, 6).a(Character.valueOf('#'), cpo.dP).b("###").b("has_snowball", mb.a(cgc.pO)).a($$0);
        ls.a(lq.b, cpo.oh).a(Character.valueOf('L'), ane.r).a(Character.valueOf('S'), cgc.oB).a(Character.valueOf('#'), ane.ah).b(" S ").b("S#S").b("LLL").b("has_soul_sand", mb.a(ane.ah)).a($$0);
        ls.a(lq.h, cgc.rE).a(Character.valueOf('#'), cgc.rt).a(Character.valueOf('X'), cgc.rh).b("###").b("#X#").b("###").b("has_melon", mb.a(cgc.rh)).a($$0);
        ls.a(lq.f, cgc.uv, 2).a(Character.valueOf('#'), cgc.qk).a(Character.valueOf('X'), cgc.nH).b(" # ").b("#X#").b(" # ").b("has_glowstone_dust", mb.a(cgc.qk)).a($$0);
        ls.a(lq.e, cgc.qj).a(Character.valueOf('#'), cgc.nO).a(Character.valueOf('X'), cgc.nS).b(" # ").b(" X ").b(" X ").b("has_amethyst_shard", mb.a(cgc.nO)).a($$0);
        ls.a(lq.i, cgc.oB, 4).a(Character.valueOf('#'), ane.b).b("#").b("#").c("sticks").b("has_planks", mb.a(ane.b)).a($$0);
        ls.a(lq.i, cgc.oB, 1).a(Character.valueOf('#'), cpo.mZ).b("#").b("#").c("sticks").b("has_bamboo", mb.a((cml)cpo.mZ)).a($$0, "stick_from_bamboo_item");
        ls.a(lq.c, cpo.br).a(Character.valueOf('P'), cpo.by).a(Character.valueOf('S'), cgc.qc).b("S").b("P").b("has_slime_ball", mb.a(cgc.qc)).a($$0);
        ls.a(lq.a, cpo.eI, 4).a(Character.valueOf('#'), cpo.b).b("##").b("##").b("has_stone", mb.a((cml)cpo.b)).a($$0);
        ls.a(lq.e, cgc.of).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.ax).b("XX").b("X#").b(" #").b("has_cobblestone", mb.a(ane.ax)).a($$0);
        mb.a(lq.a, (cml)cpo.jK, ciz.a(cpo.eI)).a("has_stone_bricks", mb.a(ane.c)).a($$0);
        mb.b((cml)cpo.fj, ciz.a(cpo.eI)).a("has_stone_bricks", mb.a(ane.c)).a($$0);
        ls.a(lq.e, cgc.og).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.ax).b("XX").b(" #").b(" #").b("has_cobblestone", mb.a(ane.ax)).a($$0);
        ls.a(lq.e, cgc.oe).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.ax).b("XXX").b(" # ").b(" # ").b("has_cobblestone", mb.a(ane.ax)).a($$0);
        ls.a(lq.e, cgc.od).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.ax).b("X").b("#").b("#").b("has_cobblestone", mb.a(ane.ax)).a($$0);
        mb.c($$0, lq.a, cpo.jE, cpo.jR);
        ls.a(lq.f, cgc.oc).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.ax).b("X").b("X").b("#").b("has_cobblestone", mb.a(ane.ax)).a($$0);
        ls.a(lq.a, cpo.bA).a(Character.valueOf('#'), cgc.oE).b("##").b("##").b("has_string", mb.a(cgc.oE)).a($$0, mb.a((cml)cpo.bA, (cml)cgc.oE));
        mb.a($$0, (cml)cgc.qM, (cml)cpo.dS, "sugar");
        lt.a(lq.i, cgc.qM, 3).b(cgc.vD).b("sugar").b("has_honey_bottle", mb.a(cgc.vD)).a($$0, mb.a((cml)cgc.qM, (cml)cgc.vD));
        ls.a(lq.c, cpo.pd).a(Character.valueOf('H'), cgc.hh).a(Character.valueOf('R'), cgc.ll).b(" R ").b("RHR").b(" R ").b("has_redstone", mb.a(cgc.ll)).b("has_hay_block", mb.a((cml)cpo.ij)).a($$0);
        ls.a(lq.c, cpo.ck).a(Character.valueOf('#'), ciz.a(cpo.I, cpo.K)).a(Character.valueOf('X'), cgc.oG).b("X#X").b("#X#").b("X#X").b("has_gunpowder", mb.a(cgc.oG)).a($$0);
        lt.a(lq.d, cgc.nd).b(cpo.ck).b(cgc.na).b("has_minecart", mb.a(cgc.na)).a($$0);
        ls.a(lq.b, cpo.cp, 4).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ciz.a(cgc.nI, cgc.nJ)).b("X").b("#").b("has_stone_pickaxe", mb.a(cgc.oe)).a($$0);
        ls.a(lq.b, cpo.eb, 4).a(Character.valueOf('X'), ciz.a(cgc.nI, cgc.nJ)).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('S'), ane.ah).b("X").b("#").b("S").b("has_soul_sand", mb.a(ane.ah)).a($$0);
        ls.a(lq.b, cpo.oe).a(Character.valueOf('#'), cgc.ej).a(Character.valueOf('X'), cgc.uB).b("XXX").b("X#X").b("XXX").b("has_iron_nugget", mb.a(cgc.uB)).b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.b, cpo.of).a(Character.valueOf('#'), cgc.eX).a(Character.valueOf('X'), cgc.uB).b("XXX").b("X#X").b("XXX").b("has_soul_torch", mb.a(cgc.eX)).a($$0);
        lt.a(lq.c, cpo.gV).b(cpo.cv).b(cpo.fH).b("has_tripwire_hook", mb.a((cml)cpo.fH)).a($$0);
        ls.a(lq.c, cpo.fH, 2).a(Character.valueOf('#'), ane.b).a(Character.valueOf('S'), cgc.oB).a(Character.valueOf('I'), cgc.nQ).b("I").b("S").b("#").b("has_string", mb.a(cgc.oE)).a($$0);
        ls.a(lq.f, cgc.nC).a(Character.valueOf('X'), cgc.nD).b("XXX").b("X X").b("has_scute", mb.a(cgc.nD)).a($$0);
        lt.a(lq.i, cgc.oI, 9).b(cpo.ij).b("has_hay_block", mb.a((cml)cpo.ij)).a($$0);
        lt.a(lq.i, cgc.qu).b(cgc.qK).b("white_dye").b("has_bone_meal", mb.a(cgc.qK)).a($$0);
        mb.a($$0, (cml)cgc.qu, (cml)cpo.ce, "white_dye");
        ls.a(lq.e, cgc.oa).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.b).b("XX").b("X#").b(" #").b("has_stick", mb.a(cgc.oB)).a($$0);
        ls.a(lq.e, cgc.ob).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.b).b("XX").b(" #").b(" #").b("has_stick", mb.a(cgc.oB)).a($$0);
        ls.a(lq.e, cgc.nZ).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.b).b("XXX").b(" # ").b(" # ").b("has_stick", mb.a(cgc.oB)).a($$0);
        ls.a(lq.e, cgc.nY).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.b).b("X").b("#").b("#").b("has_stick", mb.a(cgc.oB)).a($$0);
        ls.a(lq.f, cgc.nX).a(Character.valueOf('#'), cgc.oB).a(Character.valueOf('X'), ane.b).b("X").b("X").b("#").b("has_stick", mb.a(cgc.oB)).a($$0);
        lt.a(lq.i, cgc.tg).b(cgc.qb).b(cgc.qr).b(cgc.oF).b("has_book", mb.a(cgc.qb)).a($$0);
        mb.a($$0, (cml)cgc.qy, (cml)cpo.bR, "yellow_dye");
        mb.a($$0, cgc.qy, (cml)cpo.iD, "yellow_dye", 2);
        mb.a($$0, lq.g, (cml)cgc.ri, lq.a, cgc.pZ);
        ls.a(lq.i, cpo.mX).a(Character.valueOf('#'), cgc.uX).a(Character.valueOf('X'), cgc.uY).b("###").b("#X#").b("###").b("has_nautilus_core", mb.a(cgc.uY)).b("has_nautilus_shell", mb.a(cgc.uX)).a($$0);
        mb.d($$0, lq.b, cpo.nH, cpo.jp);
        mb.d($$0, lq.b, cpo.nK, cpo.eI);
        mb.d($$0, lq.b, cpo.nP, cpo.aV);
        lt.a(lq.i, cgc.vd).b(cgc.qa).b(cgc.tv).b("has_creeper_head", mb.a(cgc.tv)).a($$0);
        lt.a(lq.i, cgc.ve).b(cgc.qa).b(cgc.ts).b("has_wither_skeleton_skull", mb.a(cgc.ts)).a($$0);
        lt.a(lq.i, cgc.vc).b(cgc.qa).b(cpo.cb).b("has_oxeye_daisy", mb.a((cml)cpo.cb)).a($$0);
        lt.a(lq.i, cgc.vf).b(cgc.qa).b(cgc.pn).b("has_enchanted_golden_apple", mb.a(cgc.pn)).a($$0);
        ls.a(lq.b, cpo.nS, 6).a(Character.valueOf('~'), cgc.oE).a(Character.valueOf('I'), cpo.mZ).b("I~I").b("I I").b("I I").b("has_bamboo", mb.a((cml)cpo.mZ)).a($$0);
        ls.a(lq.b, cpo.nZ).a(Character.valueOf('I'), cgc.oB).a(Character.valueOf('-'), cpo.jD).a(Character.valueOf('#'), ane.b).b("I-I").b("# #").b("has_stone_slab", mb.a((cml)cpo.jD)).a($$0);
        ls.a(lq.b, cpo.nW).a(Character.valueOf('#'), cpo.jR).a(Character.valueOf('X'), cpo.cD).a(Character.valueOf('I'), cgc.nQ).b("III").b("IXI").b("###").b("has_smooth_stone", mb.a((cml)cpo.jR)).a($$0);
        ls.a(lq.b, cpo.nV).a(Character.valueOf('#'), ane.r).a(Character.valueOf('X'), cpo.cD).b(" # ").b("#X#").b(" # ").b("has_furnace", mb.a((cml)cpo.cD)).a($$0);
        ls.a(lq.b, cpo.nX).a(Character.valueOf('#'), ane.b).a(Character.valueOf('@'), cgc.qa).b("@@").b("##").b("##").b("has_paper", mb.a(cgc.qa)).a($$0);
        ls.a(lq.b, cpo.ob).a(Character.valueOf('#'), ane.b).a(Character.valueOf('@'), cgc.nQ).b("@@").b("##").b("##").b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.b, cpo.nY).a(Character.valueOf('#'), ane.b).a(Character.valueOf('@'), cgc.pi).b("@@").b("##").b("##").b("has_flint", mb.a(cgc.pi)).a($$0);
        ls.a(lq.b, cpo.oc).a(Character.valueOf('I'), cgc.nQ).a(Character.valueOf('#'), cpo.b).b(" I ").b("###").b("has_stone", mb.a((cml)cpo.b)).a($$0);
        ls.a(lq.b, cpo.pq).a(Character.valueOf('S'), cgc.fj).a(Character.valueOf('#'), cgc.nV).b("SSS").b("S#S").b("SSS").b("has_netherite_ingot", mb.a(cgc.nV)).a($$0);
        mb.b($$0, lq.i, cgc.nV, lq.a, cgc.aA, "netherite_ingot_from_netherite_block", "netherite_ingot");
        lt.a(lq.i, cgc.nV).a(cgc.nW, 4).a(cgc.nU, 4).b("netherite_ingot").b("has_netherite_scrap", mb.a(cgc.nW)).a($$0);
        ls.a(lq.b, cpo.pl).a(Character.valueOf('O'), cpo.pk).a(Character.valueOf('G'), cpo.ed).b("OOO").b("GGG").b("OOO").b("has_obsidian", mb.a((cml)cpo.pk)).a($$0);
        ls.a(lq.b, cpo.eY).a(Character.valueOf('I'), cgc.nQ).a(Character.valueOf('N'), cgc.uB).b("N").b("I").b("N").b("has_iron_nugget", mb.a(cgc.uB)).b("has_iron_ingot", mb.a(cgc.nQ)).a($$0);
        ls.a(lq.a, cpo.qB, 2).a(Character.valueOf('G'), cpo.aQ).a(Character.valueOf('S'), cgc.nO).b(" S ").b("SGS").b(" S ").b("has_amethyst_shard", mb.a(cgc.nO)).a($$0);
        mb.a($$0, lq.a, (cml)cpo.qt, (cml)cgc.nO);
        ls.a(lq.e, cgc.qf).a(Character.valueOf('C'), cgc.qe).a(Character.valueOf('S'), cgc.wu).b("SSS").b("SCS").b("SSS").b("has_echo_shard", mb.a(cgc.wu)).a($$0);
        ls.a(lq.c, cgc.lE).a(Character.valueOf('#'), cgc.nO).a(Character.valueOf('X'), cgc.lD).b(" # ").b("#X#").b("has_amethyst_shard", mb.a(cgc.nO)).a($$0);
        mb.b($$0, lq.i, cgc.uS, cgc.uU);
        ly.a(cje.c).a($$0, "armor_dye");
        ly.a(cje.k).a($$0, "banner_duplicate");
        ly.a(cje.d).a($$0, "book_cloning");
        ly.a(cje.g).a($$0, "firework_rocket");
        ly.a(cje.h).a($$0, "firework_star");
        ly.a(cje.i).a($$0, "firework_star_fade");
        ly.a(cje.e).a($$0, "map_cloning");
        ly.a(cje.f).a($$0, "map_extending");
        ly.a(cje.o).a($$0, "repair_item");
        ly.a(cje.l).a($$0, "shield_decoration");
        ly.a(cje.m).a($$0, "shulker_box_coloring");
        ly.a(cje.j).a($$0, "tipped_arrow");
        ly.a(cje.n).a($$0, "suspicious_stew");
        lu.c(ciz.a(cgc.tm), lq.g, cgc.tn, 0.35f, 200).b("has_potato", mb.a(cgc.tm)).a($$0);
        lu.c(ciz.a(cgc.pY), lq.i, cgc.pX, 0.3f, 200).b("has_clay_ball", mb.a(cgc.pY)).a($$0);
        lu.c(ciz.a(ane.q), lq.i, cgc.nJ, 0.15f, 200).b("has_log", mb.a(ane.q)).a($$0);
        lu.c(ciz.a(cgc.um), lq.i, cgc.un, 0.1f, 200).b("has_chorus_fruit", mb.a(cgc.um)).a($$0);
        lu.c(ciz.a(cgc.rl), lq.g, cgc.rm, 0.35f, 200).b("has_beef", mb.a(cgc.rl)).a($$0);
        lu.c(ciz.a(cgc.rn), lq.g, cgc.ro, 0.35f, 200).b("has_chicken", mb.a(cgc.rn)).a($$0);
        lu.c(ciz.a(cgc.ql), lq.g, cgc.qp, 0.35f, 200).b("has_cod", mb.a(cgc.ql)).a($$0);
        lu.c(ciz.a(cpo.mc), lq.g, cgc.ri, 0.1f, 200).b("has_kelp", mb.a((cml)cpo.mc)).a($$0, mb.e(cgc.ri));
        lu.c(ciz.a(cgc.qm), lq.g, cgc.qq, 0.35f, 200).b("has_salmon", mb.a(cgc.qm)).a($$0);
        lu.c(ciz.a(cgc.tT), lq.g, cgc.tU, 0.35f, 200).b("has_mutton", mb.a(cgc.tT)).a($$0);
        lu.c(ciz.a(cgc.pj), lq.g, cgc.pk, 0.35f, 200).b("has_porkchop", mb.a(cgc.pj)).a($$0);
        lu.c(ciz.a(cgc.tG), lq.g, cgc.tH, 0.35f, 200).b("has_rabbit", mb.a(cgc.tG)).a($$0);
        mb.a($$0, d, lq.i, cgc.nI, 0.1f, 200, "coal");
        mb.a($$0, e, lq.i, cgc.nQ, 0.7f, 200, "iron_ingot");
        mb.a($$0, f, lq.i, cgc.nS, 0.7f, 200, "copper_ingot");
        mb.a($$0, g, lq.i, cgc.nU, 1.0f, 200, "gold_ingot");
        mb.a($$0, h, lq.i, cgc.nK, 1.0f, 200, "diamond");
        mb.a($$0, i, lq.i, cgc.nM, 0.2f, 200, "lapis_lazuli");
        mb.a($$0, j, lq.c, cgc.ll, 0.7f, 200, "redstone");
        mb.a($$0, k, lq.i, cgc.nL, 1.0f, 200, "emerald");
        mb.a($$0, lq.i, (cml)cgc.nP, lq.a, cgc.ar);
        mb.a($$0, lq.i, (cml)cgc.nR, lq.a, cgc.as);
        mb.a($$0, lq.i, (cml)cgc.nT, lq.a, cgc.at);
        lu.c(ciz.a(ane.G), lq.a, cpo.aQ.k(), 0.1f, 200).b("has_smelts_to_glass", mb.a(ane.G)).a($$0);
        lu.c(ciz.a(cpo.mV), lq.i, cgc.qz, 0.1f, 200).b("has_sea_pickle", mb.a((cml)cpo.mV)).a($$0, mb.e(cgc.qz));
        lu.c(ciz.a(cpo.dQ.k()), lq.i, cgc.qH, 1.0f, 200).b("has_cactus", mb.a((cml)cpo.dQ)).a($$0);
        lu.c(ciz.a(cgc.oj, cgc.oi, cgc.ok, cgc.ol, cgc.oh, cgc.pa, cgc.pb, cgc.pc, cgc.pd, cgc.tN), lq.i, cgc.rt, 0.1f, 200).b("has_golden_pickaxe", mb.a(cgc.oj)).b("has_golden_shovel", mb.a(cgc.oi)).b("has_golden_axe", mb.a(cgc.ok)).b("has_golden_hoe", mb.a(cgc.ol)).b("has_golden_sword", mb.a(cgc.oh)).b("has_golden_helmet", mb.a(cgc.pa)).b("has_golden_chestplate", mb.a(cgc.pb)).b("has_golden_leggings", mb.a(cgc.pc)).b("has_golden_boots", mb.a(cgc.pd)).b("has_golden_horse_armor", mb.a(cgc.tN)).a($$0, mb.e(cgc.rt));
        lu.c(ciz.a(cgc.oo, cgc.on, cgc.op, cgc.oq, cgc.om, cgc.oS, cgc.oT, cgc.oU, cgc.oV, cgc.tM, cgc.oO, cgc.oP, cgc.oQ, cgc.oR), lq.i, cgc.uB, 0.1f, 200).b("has_iron_pickaxe", mb.a(cgc.oo)).b("has_iron_shovel", mb.a(cgc.on)).b("has_iron_axe", mb.a(cgc.op)).b("has_iron_hoe", mb.a(cgc.oq)).b("has_iron_sword", mb.a(cgc.om)).b("has_iron_helmet", mb.a(cgc.oS)).b("has_iron_chestplate", mb.a(cgc.oT)).b("has_iron_leggings", mb.a(cgc.oU)).b("has_iron_boots", mb.a(cgc.oV)).b("has_iron_horse_armor", mb.a(cgc.tM)).b("has_chainmail_helmet", mb.a(cgc.oO)).b("has_chainmail_chestplate", mb.a(cgc.oP)).b("has_chainmail_leggings", mb.a(cgc.oQ)).b("has_chainmail_boots", mb.a(cgc.oR)).a($$0, mb.e(cgc.uB));
        lu.c(ciz.a(cpo.dR), lq.a, cpo.iA.k(), 0.35f, 200).b("has_clay_block", mb.a((cml)cpo.dR)).a($$0);
        lu.c(ciz.a(cpo.dW), lq.i, cgc.tD, 0.1f, 200).b("has_netherrack", mb.a((cml)cpo.dW)).a($$0);
        lu.c(ciz.a(cpo.hb), lq.i, cgc.nN, 0.2f, 200).b("has_nether_quartz_ore", mb.a((cml)cpo.hb)).a($$0);
        lu.c(ciz.a(cpo.aP), lq.a, cpo.aO.k(), 0.15f, 200).b("has_wet_sponge", mb.a((cml)cpo.aP)).a($$0);
        lu.c(ciz.a(cpo.m), lq.a, cpo.b.k(), 0.1f, 200).b("has_cobblestone", mb.a((cml)cpo.m)).a($$0);
        lu.c(ciz.a(cpo.b), lq.a, cpo.jR.k(), 0.1f, 200).b("has_stone", mb.a((cml)cpo.b)).a($$0);
        lu.c(ciz.a(cpo.aV), lq.a, cpo.jS.k(), 0.1f, 200).b("has_sandstone", mb.a((cml)cpo.aV)).a($$0);
        lu.c(ciz.a(cpo.jp), lq.a, cpo.jU.k(), 0.1f, 200).b("has_red_sandstone", mb.a((cml)cpo.jp)).a($$0);
        lu.c(ciz.a(cpo.hd), lq.a, cpo.jT.k(), 0.1f, 200).b("has_quartz_block", mb.a((cml)cpo.hd)).a($$0);
        lu.c(ciz.a(cpo.eI), lq.a, cpo.eK.k(), 0.1f, 200).b("has_stone_bricks", mb.a((cml)cpo.eI)).a($$0);
        lu.c(ciz.a(cpo.hy), lq.b, cpo.lv.k(), 0.1f, 200).b("has_black_terracotta", mb.a((cml)cpo.hy)).a($$0);
        lu.c(ciz.a(cpo.hu), lq.b, cpo.lr.k(), 0.1f, 200).b("has_blue_terracotta", mb.a((cml)cpo.hu)).a($$0);
        lu.c(ciz.a(cpo.hv), lq.b, cpo.ls.k(), 0.1f, 200).b("has_brown_terracotta", mb.a((cml)cpo.hv)).a($$0);
        lu.c(ciz.a(cpo.hs), lq.b, cpo.lp.k(), 0.1f, 200).b("has_cyan_terracotta", mb.a((cml)cpo.hs)).a($$0);
        lu.c(ciz.a(cpo.hq), lq.b, cpo.ln.k(), 0.1f, 200).b("has_gray_terracotta", mb.a((cml)cpo.hq)).a($$0);
        lu.c(ciz.a(cpo.hw), lq.b, cpo.lt.k(), 0.1f, 200).b("has_green_terracotta", mb.a((cml)cpo.hw)).a($$0);
        lu.c(ciz.a(cpo.hm), lq.b, cpo.lj.k(), 0.1f, 200).b("has_light_blue_terracotta", mb.a((cml)cpo.hm)).a($$0);
        lu.c(ciz.a(cpo.hr), lq.b, cpo.lo.k(), 0.1f, 200).b("has_light_gray_terracotta", mb.a((cml)cpo.hr)).a($$0);
        lu.c(ciz.a(cpo.ho), lq.b, cpo.ll.k(), 0.1f, 200).b("has_lime_terracotta", mb.a((cml)cpo.ho)).a($$0);
        lu.c(ciz.a(cpo.hl), lq.b, cpo.li.k(), 0.1f, 200).b("has_magenta_terracotta", mb.a((cml)cpo.hl)).a($$0);
        lu.c(ciz.a(cpo.hk), lq.b, cpo.lh.k(), 0.1f, 200).b("has_orange_terracotta", mb.a((cml)cpo.hk)).a($$0);
        lu.c(ciz.a(cpo.hp), lq.b, cpo.lm.k(), 0.1f, 200).b("has_pink_terracotta", mb.a((cml)cpo.hp)).a($$0);
        lu.c(ciz.a(cpo.ht), lq.b, cpo.lq.k(), 0.1f, 200).b("has_purple_terracotta", mb.a((cml)cpo.ht)).a($$0);
        lu.c(ciz.a(cpo.hx), lq.b, cpo.lu.k(), 0.1f, 200).b("has_red_terracotta", mb.a((cml)cpo.hx)).a($$0);
        lu.c(ciz.a(cpo.hj), lq.b, cpo.lg.k(), 0.1f, 200).b("has_white_terracotta", mb.a((cml)cpo.hj)).a($$0);
        lu.c(ciz.a(cpo.hn), lq.b, cpo.lk.k(), 0.1f, 200).b("has_yellow_terracotta", mb.a((cml)cpo.hn)).a($$0);
        lu.c(ciz.a(cpo.pj), lq.i, cgc.nW, 2.0f, 200).b("has_ancient_debris", mb.a((cml)cpo.pj)).a($$0);
        lu.c(ciz.a(cpo.dZ), lq.a, cpo.sd, 0.1f, 200).b("has_basalt", mb.a((cml)cpo.dZ)).a($$0);
        lu.c(ciz.a(cpo.rJ), lq.a, cpo.rI, 0.1f, 200).b("has_cobbled_deepslate", mb.a((cml)cpo.rJ)).a($$0);
        mb.b($$0, d, lq.i, cgc.nI, 0.1f, 100, "coal");
        mb.b($$0, e, lq.i, cgc.nQ, 0.7f, 100, "iron_ingot");
        mb.b($$0, f, lq.i, cgc.nS, 0.7f, 100, "copper_ingot");
        mb.b($$0, g, lq.i, cgc.nU, 1.0f, 100, "gold_ingot");
        mb.b($$0, h, lq.i, cgc.nK, 1.0f, 100, "diamond");
        mb.b($$0, i, lq.i, cgc.nM, 0.2f, 100, "lapis_lazuli");
        mb.b($$0, j, lq.c, cgc.ll, 0.7f, 100, "redstone");
        mb.b($$0, k, lq.i, cgc.nL, 1.0f, 100, "emerald");
        lu.b(ciz.a(cpo.hb), lq.i, cgc.nN, 0.2f, 100).b("has_nether_quartz_ore", mb.a((cml)cpo.hb)).a($$0, mb.f(cgc.nN));
        lu.b(ciz.a(cgc.oj, cgc.oi, cgc.ok, cgc.ol, cgc.oh, cgc.pa, cgc.pb, cgc.pc, cgc.pd, cgc.tN), lq.i, cgc.rt, 0.1f, 100).b("has_golden_pickaxe", mb.a(cgc.oj)).b("has_golden_shovel", mb.a(cgc.oi)).b("has_golden_axe", mb.a(cgc.ok)).b("has_golden_hoe", mb.a(cgc.ol)).b("has_golden_sword", mb.a(cgc.oh)).b("has_golden_helmet", mb.a(cgc.pa)).b("has_golden_chestplate", mb.a(cgc.pb)).b("has_golden_leggings", mb.a(cgc.pc)).b("has_golden_boots", mb.a(cgc.pd)).b("has_golden_horse_armor", mb.a(cgc.tN)).a($$0, mb.f(cgc.rt));
        lu.b(ciz.a(cgc.oo, cgc.on, cgc.op, cgc.oq, cgc.om, cgc.oS, cgc.oT, cgc.oU, cgc.oV, cgc.tM, cgc.oO, cgc.oP, cgc.oQ, cgc.oR), lq.i, cgc.uB, 0.1f, 100).b("has_iron_pickaxe", mb.a(cgc.oo)).b("has_iron_shovel", mb.a(cgc.on)).b("has_iron_axe", mb.a(cgc.op)).b("has_iron_hoe", mb.a(cgc.oq)).b("has_iron_sword", mb.a(cgc.om)).b("has_iron_helmet", mb.a(cgc.oS)).b("has_iron_chestplate", mb.a(cgc.oT)).b("has_iron_leggings", mb.a(cgc.oU)).b("has_iron_boots", mb.a(cgc.oV)).b("has_iron_horse_armor", mb.a(cgc.tM)).b("has_chainmail_helmet", mb.a(cgc.oO)).b("has_chainmail_chestplate", mb.a(cgc.oP)).b("has_chainmail_leggings", mb.a(cgc.oQ)).b("has_chainmail_boots", mb.a(cgc.oR)).a($$0, mb.f(cgc.uB));
        lu.b(ciz.a(cpo.pj), lq.i, cgc.nW, 2.0f, 100).b("has_ancient_debris", mb.a((cml)cpo.pj)).a($$0, mb.f(cgc.nW));
        mb.a($$0, "smoking", cje.r, 100);
        mb.a($$0, "campfire_cooking", cje.s, 600);
        mb.a($$0, lq.a, (cml)cpo.jD, (cml)cpo.b, 2);
        mb.i($$0, lq.a, cpo.nk, cpo.b);
        mb.i($$0, lq.a, cpo.eI, cpo.b);
        mb.a($$0, lq.a, (cml)cpo.jK, (cml)cpo.b, 2);
        mb.i($$0, lq.a, cpo.fj, cpo.b);
        lv.a(ciz.a(cpo.b), lq.a, cpo.eL).b("has_stone", mb.a((cml)cpo.b)).a($$0, "chiseled_stone_bricks_stone_from_stonecutting");
        lv.a(ciz.a(cpo.b), lq.b, cpo.nK).b("has_stone", mb.a((cml)cpo.b)).a($$0, "stone_brick_walls_from_stone_stonecutting");
        mb.i($$0, lq.a, cpo.aX, cpo.aV);
        mb.a($$0, lq.a, (cml)cpo.jF, (cml)cpo.aV, 2);
        mb.a($$0, lq.a, (cml)cpo.jG, (cml)cpo.aV, 2);
        mb.a($$0, lq.a, (cml)cpo.jG, (cml)cpo.aX, 2);
        mb.i($$0, lq.a, cpo.fD, cpo.aV);
        mb.i($$0, lq.b, cpo.nP, cpo.aV);
        mb.i($$0, lq.a, cpo.aW, cpo.aV);
        mb.i($$0, lq.a, cpo.jr, cpo.jp);
        mb.a($$0, lq.a, (cml)cpo.jO, (cml)cpo.jp, 2);
        mb.a($$0, lq.a, (cml)cpo.jP, (cml)cpo.jp, 2);
        mb.a($$0, lq.a, (cml)cpo.jP, (cml)cpo.jr, 2);
        mb.i($$0, lq.a, cpo.js, cpo.jp);
        mb.i($$0, lq.b, cpo.nH, cpo.jp);
        mb.i($$0, lq.a, cpo.jq, cpo.jp);
        lv.a(ciz.a(cpo.hd), lq.a, cpo.jN, 2).b("has_quartz_block", mb.a((cml)cpo.hd)).a($$0, "quartz_slab_from_stonecutting");
        mb.i($$0, lq.a, cpo.hg, cpo.hd);
        mb.i($$0, lq.a, cpo.hf, cpo.hd);
        mb.i($$0, lq.a, cpo.he, cpo.hd);
        mb.i($$0, lq.a, cpo.pK, cpo.hd);
        mb.i($$0, lq.a, cpo.cQ, cpo.m);
        mb.a($$0, lq.a, (cml)cpo.jI, (cml)cpo.m, 2);
        mb.i($$0, lq.b, cpo.fP, cpo.m);
        mb.a($$0, lq.a, (cml)cpo.jK, (cml)cpo.eI, 2);
        mb.i($$0, lq.a, cpo.fj, cpo.eI);
        lv.a(ciz.a(cpo.eI), lq.b, cpo.nK).b("has_stone_bricks", mb.a((cml)cpo.eI)).a($$0, "stone_brick_wall_from_stone_bricks_stonecutting");
        mb.i($$0, lq.a, cpo.eL, cpo.eI);
        mb.a($$0, lq.a, (cml)cpo.jJ, (cml)cpo.cj, 2);
        mb.i($$0, lq.a, cpo.fi, cpo.cj);
        mb.i($$0, lq.b, cpo.nF, cpo.cj);
        mb.a($$0, lq.a, (cml)cpo.jL, (cml)cpo.eN, 2);
        mb.i($$0, lq.a, cpo.fk, cpo.eN);
        mb.i($$0, lq.b, cpo.nL, cpo.eN);
        mb.a($$0, lq.a, (cml)cpo.jM, (cml)cpo.fn, 2);
        mb.i($$0, lq.a, cpo.fp, cpo.fn);
        mb.i($$0, lq.b, cpo.nM, cpo.fn);
        mb.i($$0, lq.a, cpo.pI, cpo.fn);
        mb.a($$0, lq.a, (cml)cpo.nC, (cml)cpo.kL, 2);
        mb.i($$0, lq.a, cpo.np, cpo.kL);
        mb.i($$0, lq.b, cpo.nO, cpo.kL);
        mb.a($$0, lq.a, (cml)cpo.jQ, (cml)cpo.kw, 2);
        mb.i($$0, lq.a, cpo.ky, cpo.kw);
        mb.i($$0, lq.a, cpo.kx, cpo.kw);
        mb.a($$0, lq.a, (cml)cpo.if, (cml)cpo.hZ, 2);
        mb.i($$0, lq.a, cpo.ic, cpo.hZ);
        mb.i($$0, lq.b, cpo.nG, cpo.hZ);
        lv.a(ciz.a(cpo.ia), lq.a, cpo.ig, 2).b("has_prismarine_brick", mb.a((cml)cpo.ia)).a($$0, "prismarine_brick_slab_from_prismarine_stonecutting");
        lv.a(ciz.a(cpo.ia), lq.a, cpo.id).b("has_prismarine_brick", mb.a((cml)cpo.ia)).a($$0, "prismarine_brick_stairs_from_prismarine_stonecutting");
        mb.a($$0, lq.a, (cml)cpo.ih, (cml)cpo.ib, 2);
        mb.i($$0, lq.a, cpo.ie, cpo.ib);
        mb.a($$0, lq.a, (cml)cpo.nB, (cml)cpo.g, 2);
        mb.i($$0, lq.a, cpo.no, cpo.g);
        mb.i($$0, lq.b, cpo.nN, cpo.g);
        mb.i($$0, lq.a, cpo.h, cpo.g);
        mb.a($$0, lq.a, (cml)cpo.nD, (cml)cpo.g, 2);
        mb.i($$0, lq.a, cpo.nq, cpo.g);
        mb.a($$0, lq.a, (cml)cpo.nD, (cml)cpo.h, 2);
        mb.i($$0, lq.a, cpo.nq, cpo.h);
        mb.i($$0, lq.a, cpo.ea, cpo.dZ);
        mb.a($$0, lq.a, (cml)cpo.nA, (cml)cpo.c, 2);
        mb.i($$0, lq.a, cpo.nn, cpo.c);
        mb.i($$0, lq.b, cpo.nJ, cpo.c);
        mb.i($$0, lq.a, cpo.d, cpo.c);
        mb.a($$0, lq.a, (cml)cpo.ns, (cml)cpo.c, 2);
        mb.i($$0, lq.a, cpo.ne, cpo.c);
        mb.a($$0, lq.a, (cml)cpo.ns, (cml)cpo.d, 2);
        mb.i($$0, lq.a, cpo.ne, cpo.d);
        mb.a($$0, lq.a, (cml)cpo.nE, (cml)cpo.e, 2);
        mb.i($$0, lq.a, cpo.nr, cpo.e);
        mb.i($$0, lq.b, cpo.nR, cpo.e);
        mb.i($$0, lq.a, cpo.f, cpo.e);
        mb.a($$0, lq.a, (cml)cpo.nv, (cml)cpo.e, 2);
        mb.i($$0, lq.a, cpo.nh, cpo.e);
        mb.a($$0, lq.a, (cml)cpo.nv, (cml)cpo.f, 2);
        mb.i($$0, lq.a, cpo.nh, cpo.f);
        lv.a(ciz.a(cpo.eJ), lq.a, cpo.nu, 2).b("has_mossy_stone_bricks", mb.a((cml)cpo.eJ)).a($$0, "mossy_stone_brick_slab_from_mossy_stone_brick_stonecutting");
        lv.a(ciz.a(cpo.eJ), lq.a, cpo.ng).b("has_mossy_stone_bricks", mb.a((cml)cpo.eJ)).a($$0, "mossy_stone_brick_stairs_from_mossy_stone_brick_stonecutting");
        lv.a(ciz.a(cpo.eJ), lq.b, cpo.nI).b("has_mossy_stone_bricks", mb.a((cml)cpo.eJ)).a($$0, "mossy_stone_brick_wall_from_mossy_stone_brick_stonecutting");
        mb.a($$0, lq.a, (cml)cpo.nw, (cml)cpo.cn, 2);
        mb.i($$0, lq.a, cpo.ni, cpo.cn);
        mb.i($$0, lq.b, cpo.fQ, cpo.cn);
        mb.a($$0, lq.a, (cml)cpo.ny, (cml)cpo.jS, 2);
        mb.i($$0, lq.a, cpo.nl, cpo.jS);
        mb.a($$0, lq.a, (cml)cpo.nt, (cml)cpo.jU, 2);
        mb.i($$0, lq.a, cpo.nf, cpo.jU);
        mb.a($$0, lq.a, (cml)cpo.nz, (cml)cpo.jT, 2);
        mb.i($$0, lq.a, cpo.nm, cpo.jT);
        lv.a(ciz.a(cpo.kz), lq.a, cpo.nx, 2).b("has_end_stone_brick", mb.a((cml)cpo.kz)).a($$0, "end_stone_brick_slab_from_end_stone_brick_stonecutting");
        lv.a(ciz.a(cpo.kz), lq.a, cpo.nj).b("has_end_stone_brick", mb.a((cml)cpo.kz)).a($$0, "end_stone_brick_stairs_from_end_stone_brick_stonecutting");
        lv.a(ciz.a(cpo.kz), lq.b, cpo.nQ).b("has_end_stone_brick", mb.a((cml)cpo.kz)).a($$0, "end_stone_brick_wall_from_end_stone_brick_stonecutting");
        mb.i($$0, lq.a, cpo.kz, cpo.fz);
        mb.a($$0, lq.a, (cml)cpo.nx, (cml)cpo.fz, 2);
        mb.i($$0, lq.a, cpo.nj, cpo.fz);
        mb.i($$0, lq.b, cpo.nQ, cpo.fz);
        mb.a($$0, lq.a, (cml)cpo.jE, (cml)cpo.jR, 2);
        mb.a($$0, lq.a, (cml)cpo.pu, (cml)cpo.pr, 2);
        mb.i($$0, lq.a, cpo.ps, cpo.pr);
        mb.i($$0, lq.b, cpo.pt, cpo.pr);
        mb.i($$0, lq.a, cpo.pv, cpo.pr);
        mb.i($$0, lq.b, cpo.pH, cpo.pr);
        mb.a($$0, lq.a, (cml)cpo.pE, (cml)cpo.pr, 2);
        mb.i($$0, lq.a, cpo.pD, cpo.pr);
        mb.i($$0, lq.a, cpo.py, cpo.pr);
        mb.i($$0, lq.a, cpo.pw, cpo.pr);
        mb.a($$0, lq.a, (cml)cpo.pz, (cml)cpo.pr, 2);
        mb.i($$0, lq.a, cpo.pA, cpo.pr);
        mb.i($$0, lq.b, cpo.pB, cpo.pr);
        mb.a($$0, lq.a, (cml)cpo.pE, (cml)cpo.pv, 2);
        mb.i($$0, lq.a, cpo.pD, cpo.pv);
        mb.i($$0, lq.a, cpo.pw, cpo.pv);
        mb.i($$0, lq.b, cpo.pH, cpo.pv);
        mb.a($$0, lq.a, (cml)cpo.pz, (cml)cpo.pv, 2);
        mb.i($$0, lq.a, cpo.pA, cpo.pv);
        mb.i($$0, lq.b, cpo.pB, cpo.pv);
        mb.i($$0, lq.a, cpo.py, cpo.pv);
        mb.a($$0, lq.a, (cml)cpo.pz, (cml)cpo.pw, 2);
        mb.i($$0, lq.a, cpo.pA, cpo.pw);
        mb.i($$0, lq.b, cpo.pB, cpo.pw);
        mb.a($$0, lq.a, (cml)cpo.ra, (cml)cpo.qS, 2);
        mb.i($$0, lq.a, cpo.qW, cpo.qS);
        mb.a($$0, lq.a, (cml)cpo.qZ, (cml)cpo.qR, 2);
        mb.i($$0, lq.a, cpo.qV, cpo.qR);
        mb.a($$0, lq.a, (cml)cpo.qY, (cml)cpo.qQ, 2);
        mb.i($$0, lq.a, cpo.qU, cpo.qQ);
        mb.a($$0, lq.a, (cml)cpo.qX, (cml)cpo.qP, 2);
        mb.i($$0, lq.a, cpo.qT, cpo.qP);
        mb.a($$0, lq.a, (cml)cpo.rq, (cml)cpo.ri, 2);
        mb.i($$0, lq.a, cpo.rm, cpo.ri);
        mb.a($$0, lq.a, (cml)cpo.rp, (cml)cpo.rh, 2);
        mb.i($$0, lq.a, cpo.rl, cpo.rh);
        mb.a($$0, lq.a, (cml)cpo.ro, (cml)cpo.rg, 2);
        mb.i($$0, lq.a, cpo.rk, cpo.rg);
        mb.a($$0, lq.a, (cml)cpo.rn, (cml)cpo.rf, 2);
        mb.i($$0, lq.a, cpo.rj, cpo.rf);
        mb.a($$0, lq.a, (cml)cpo.qS, (cml)cpo.qM, 4);
        mb.a($$0, lq.a, (cml)cpo.qW, (cml)cpo.qM, 4);
        mb.a($$0, lq.a, (cml)cpo.ra, (cml)cpo.qM, 8);
        mb.a($$0, lq.a, (cml)cpo.qR, (cml)cpo.qL, 4);
        mb.a($$0, lq.a, (cml)cpo.qV, (cml)cpo.qL, 4);
        mb.a($$0, lq.a, (cml)cpo.qZ, (cml)cpo.qL, 8);
        mb.a($$0, lq.a, (cml)cpo.qQ, (cml)cpo.qK, 4);
        mb.a($$0, lq.a, (cml)cpo.qU, (cml)cpo.qK, 4);
        mb.a($$0, lq.a, (cml)cpo.qY, (cml)cpo.qK, 8);
        mb.a($$0, lq.a, (cml)cpo.qP, (cml)cpo.qJ, 4);
        mb.a($$0, lq.a, (cml)cpo.qT, (cml)cpo.qJ, 4);
        mb.a($$0, lq.a, (cml)cpo.qX, (cml)cpo.qJ, 8);
        mb.a($$0, lq.a, (cml)cpo.ri, (cml)cpo.rb, 4);
        mb.a($$0, lq.a, (cml)cpo.rm, (cml)cpo.rb, 4);
        mb.a($$0, lq.a, (cml)cpo.rq, (cml)cpo.rb, 8);
        mb.a($$0, lq.a, (cml)cpo.rh, (cml)cpo.rd, 4);
        mb.a($$0, lq.a, (cml)cpo.rl, (cml)cpo.rd, 4);
        mb.a($$0, lq.a, (cml)cpo.rp, (cml)cpo.rd, 8);
        mb.a($$0, lq.a, (cml)cpo.rg, (cml)cpo.rc, 4);
        mb.a($$0, lq.a, (cml)cpo.rk, (cml)cpo.rc, 4);
        mb.a($$0, lq.a, (cml)cpo.ro, (cml)cpo.rc, 8);
        mb.a($$0, lq.a, (cml)cpo.rf, (cml)cpo.re, 4);
        mb.a($$0, lq.a, (cml)cpo.rj, (cml)cpo.re, 4);
        mb.a($$0, lq.a, (cml)cpo.rn, (cml)cpo.re, 8);
        mb.a($$0, lq.a, (cml)cpo.rL, (cml)cpo.rJ, 2);
        mb.i($$0, lq.a, cpo.rK, cpo.rJ);
        mb.i($$0, lq.b, cpo.rM, cpo.rJ);
        mb.i($$0, lq.a, cpo.rZ, cpo.rJ);
        mb.i($$0, lq.a, cpo.rN, cpo.rJ);
        mb.a($$0, lq.a, (cml)cpo.rP, (cml)cpo.rJ, 2);
        mb.i($$0, lq.a, cpo.rO, cpo.rJ);
        mb.i($$0, lq.b, cpo.rQ, cpo.rJ);
        mb.i($$0, lq.a, cpo.rV, cpo.rJ);
        mb.a($$0, lq.a, (cml)cpo.rX, (cml)cpo.rJ, 2);
        mb.i($$0, lq.a, cpo.rW, cpo.rJ);
        mb.i($$0, lq.b, cpo.rY, cpo.rJ);
        mb.i($$0, lq.a, cpo.rR, cpo.rJ);
        mb.a($$0, lq.a, (cml)cpo.rT, (cml)cpo.rJ, 2);
        mb.i($$0, lq.a, cpo.rS, cpo.rJ);
        mb.i($$0, lq.b, cpo.rU, cpo.rJ);
        mb.a($$0, lq.a, (cml)cpo.rP, (cml)cpo.rN, 2);
        mb.i($$0, lq.a, cpo.rO, cpo.rN);
        mb.i($$0, lq.b, cpo.rQ, cpo.rN);
        mb.i($$0, lq.a, cpo.rV, cpo.rN);
        mb.a($$0, lq.a, (cml)cpo.rX, (cml)cpo.rN, 2);
        mb.i($$0, lq.a, cpo.rW, cpo.rN);
        mb.i($$0, lq.b, cpo.rY, cpo.rN);
        mb.i($$0, lq.a, cpo.rR, cpo.rN);
        mb.a($$0, lq.a, (cml)cpo.rT, (cml)cpo.rN, 2);
        mb.i($$0, lq.a, cpo.rS, cpo.rN);
        mb.i($$0, lq.b, cpo.rU, cpo.rN);
        mb.a($$0, lq.a, (cml)cpo.rX, (cml)cpo.rV, 2);
        mb.i($$0, lq.a, cpo.rW, cpo.rV);
        mb.i($$0, lq.b, cpo.rY, cpo.rV);
        mb.i($$0, lq.a, cpo.rR, cpo.rV);
        mb.a($$0, lq.a, (cml)cpo.rT, (cml)cpo.rV, 2);
        mb.i($$0, lq.a, cpo.rS, cpo.rV);
        mb.i($$0, lq.b, cpo.rU, cpo.rV);
        mb.a($$0, lq.a, (cml)cpo.rT, (cml)cpo.rR, 2);
        mb.i($$0, lq.a, cpo.rS, cpo.rR);
        mb.i($$0, lq.b, cpo.rU, cpo.rR);
        mb.b().forEach(($$1, $$2) -> mb.a($$0, $$1, $$2));
        mb.a($$0, cgc.oX, lq.f, cgc.pf);
        mb.a($$0, cgc.oY, lq.f, cgc.pg);
        mb.a($$0, cgc.oW, lq.f, cgc.pe);
        mb.a($$0, cgc.oZ, lq.f, cgc.ph);
        mb.a($$0, cgc.or, lq.f, cgc.ow);
        mb.a($$0, cgc.ou, lq.e, cgc.oz);
        mb.a($$0, cgc.ot, lq.e, cgc.oy);
        mb.a($$0, cgc.ov, lq.e, cgc.oA);
        mb.a($$0, cgc.os, lq.e, cgc.ox);
        mb.o($$0, cgc.ww, cgc.eR);
        mb.o($$0, cgc.wx, cgc.w);
        mb.o($$0, cgc.wy, cgc.cn);
        mb.o($$0, cgc.wz, cgc.w);
        mb.o($$0, cgc.wA, cgc.eh);
        mb.o($$0, cgc.wB, cgc.j);
        mb.o($$0, cgc.wC, cgc.fR);
        mb.o($$0, cgc.wD, cgc.w);
        mb.o($$0, cgc.wE, cgc.in);
        mb.o($$0, cgc.wF, cgc.vH);
        mb.o($$0, cgc.wG, cgc.eR);
        mb.o($$0, cgc.wH, cgc.en);
        mb.o($$0, cgc.wK, cgc.j);
        mb.o($$0, cgc.wI, cgc.hy);
        mb.o($$0, cgc.wJ, cgc.hy);
        mb.o($$0, cgc.wL, cgc.hy);
        mb.o($$0, cgc.wM, cgc.hy);
        mb.b($$0, lq.a, cpo.ae, cgc.dv);
        mb.b($$0, cpo.v, ane.C, 2);
        mb.h($$0, lq.b, cpo.w, cpo.jB);
        mb.b($$0, (cml)cgc.ny, cpo.v);
        mb.c($$0, (cml)cgc.nz, cgc.ny);
        mb.e($$0, (cml)cgc.pz, cpo.al);
        mb.e($$0, (cml)cgc.pA, cpo.af);
        mb.e($$0, (cml)cgc.pB, cpo.ag);
        mb.e($$0, (cml)cgc.pC, cpo.ah);
        mb.e($$0, (cml)cgc.pD, cpo.ai);
        mb.e($$0, (cml)cgc.pE, cpo.aj);
        mb.e($$0, (cml)cgc.pF, cpo.ak);
        mb.e($$0, (cml)cgc.pG, cpo.am);
        mb.e($$0, (cml)cgc.pH, cgc.bN);
        mb.e($$0, (cml)cgc.pI, cpo.ot);
        mb.e($$0, (cml)cgc.pJ, cpo.ok);
        ls.a(lq.a, cpo.cm).a(Character.valueOf('#'), ane.b).a(Character.valueOf('X'), ane.j).b("###").b("XXX").b("###").b("has_book", mb.a(cgc.qb)).a($$0);
        mb.a($$0, (cml)cgc.qv, (cml)cpo.bS, "orange_dye");
        mb.a($$0, cgc.qD, (cml)cpo.kC, "cyan_dye", 2);
        mb.a($$0, (cml)cpo.s, ane.w, 4);
        mb.a($$0, (cml)cpo.at, (cml)cpo.Z);
        mb.a($$0, (cml)cpo.aB, (cml)cpo.aj);
        mb.b($$0, (cml)cgc.ns, cpo.s);
        mb.c($$0, (cml)cgc.nt, cgc.ns);
        mb.a($$0, cgc.qA, (cml)cgc.dq, "pink_dye", 1);
        ls.a(lq.e, cgc.wv).a(Character.valueOf('X'), cgc.oF).a(Character.valueOf('#'), cgc.nS).a(Character.valueOf('I'), cgc.oB).b("X").b("#").b("I").b("has_copper_ingot", mb.a(cgc.nS)).a($$0);
        ls.a(lq.b, cgc.eg).a(Character.valueOf('#'), cgc.pX).b(" # ").b("# #").b(" # ").b("has_brick", mb.a(ane.aM)).a($$0, "decorated_pot_simple");
        ly.a(cje.w).a($$0, "decorated_pot");
    }

    public static Map<cfu, acq> b() {
        return Stream.of(cgc.wE, cgc.wF, cgc.wz, cgc.wD, cgc.wH, cgc.wB, cgc.wC, cgc.wy, cgc.wA, cgc.wG, cgc.wx, cgc.wI, cgc.wJ, cgc.wK, cgc.wL, cgc.wM).collect(Collectors.toMap(Function.identity(), $$0 -> new acq(mb.c($$0) + "_smithing_trim")));
    }
}

