/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class ne {
    public static void a(nm<dtj> $$0) {
        hf<dre> $$1 = $$0.a(jc.ay);
        he.c<dre> $$2 = $$1.b(ow.s);
        hf<dvr> $$3 = $$0.a(jc.aA);
        he.c<dvr> $$4 = $$3.b(nu.H);
        he.c<dvr> $$5 = $$3.b(nu.I);
        hf<dtj> $$6 = $$0.a(jc.aC);
        he.c<dtj> $$7 = $$6.b(nt.a);
        nt.a($$0, "ancient_city/structures", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.g(), (Object)7), (Object)Pair.of(dth.b("ancient_city/structures/barracks", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/chamber_1", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/chamber_2", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/chamber_3", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/sauna_1", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/small_statue", $$4), (Object)4), (Object)Pair.of(dth.b("ancient_city/structures/large_ruin_1", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/structures/tall_ruin_1", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/structures/tall_ruin_2", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/structures/tall_ruin_3", $$4), (Object)2), (Object)Pair.of(dth.b("ancient_city/structures/tall_ruin_4", $$4), (Object)2), (Object[])new Pair[]{Pair.of(dth.a((List<Function<dtj.a, ? extends dth>>)ImmutableList.of(dth.b("ancient_city/structures/camp_1", $$4), dth.b("ancient_city/structures/camp_2", $$4), dth.b("ancient_city/structures/camp_3", $$4))), (Object)1), Pair.of(dth.b("ancient_city/structures/medium_ruin_1", $$4), (Object)1), Pair.of(dth.b("ancient_city/structures/medium_ruin_2", $$4), (Object)1), Pair.of(dth.b("ancient_city/structures/small_ruin_1", $$4), (Object)1), Pair.of(dth.b("ancient_city/structures/small_ruin_2", $$4), (Object)1), Pair.of(dth.b("ancient_city/structures/large_pillar_1", $$4), (Object)1), Pair.of(dth.b("ancient_city/structures/medium_pillar_1", $$4), (Object)1), Pair.of(dth.a((List<Function<dtj.a, ? extends dth>>)ImmutableList.of(dth.b("ancient_city/structures/ice_box_1"))), (Object)1)}), dtj.a.b));
        nt.a($$0, "ancient_city/sculk", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a($$2), (Object)6), (Object)Pair.of(dth.g(), (Object)1)), dtj.a.b));
        nt.a($$0, "ancient_city/walls", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("ancient_city/walls/intact_corner_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_intersection_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_lshape_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_2", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_2", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_3", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_4", $$5), (Object)4), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_passage_1", $$5), (Object)3), (Object)Pair.of(dth.b("ancient_city/walls/ruined_corner_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/ruined_corner_wall_2", $$5), (Object)1), (Object[])new Pair[]{Pair.of(dth.b("ancient_city/walls/ruined_horizontal_wall_stairs_1", $$5), (Object)2), Pair.of(dth.b("ancient_city/walls/ruined_horizontal_wall_stairs_2", $$5), (Object)2), Pair.of(dth.b("ancient_city/walls/ruined_horizontal_wall_stairs_3", $$5), (Object)3), Pair.of(dth.b("ancient_city/walls/ruined_horizontal_wall_stairs_4", $$5), (Object)3)}), dtj.a.b));
        nt.a($$0, "ancient_city/walls/no_corners", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_2", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_1", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_2", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_3", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_4", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_stairs_5", $$5), (Object)1), (Object)Pair.of(dth.b("ancient_city/walls/intact_horizontal_wall_bridge", $$5), (Object)1)), dtj.a.b));
        nt.a($$0, "ancient_city/city_center/walls", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("ancient_city/city_center/walls/bottom_1", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/bottom_2", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/bottom_left_corner", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/bottom_right_corner_1", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/bottom_right_corner_2", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/left", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/right", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/top", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/top_right_corner", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city_center/walls/top_left_corner", $$4), (Object)1)), dtj.a.b));
        nt.a($$0, "ancient_city/city/entrance", new dtj($$7, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_connector", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_path_1", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_path_2", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_path_3", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_path_4", $$4), (Object)1), (Object)Pair.of(dth.b("ancient_city/city/entrance/entrance_path_5", $$4), (Object)1)), dtj.a.b));
    }
}

