/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class ng {
    public static void a(nm<dtj> $$0) {
        hf<dvr> $$1 = $$0.a(jc.aA);
        he.c<dvr> $$2 = $$1.b(nu.v);
        he.c<dvr> $$3 = $$1.b(nu.u);
        hf<dtj> $$4 = $$0.a(jc.aC);
        he.c<dtj> $$5 = $$4.b(nt.a);
        nt.a($$0, "bastion/hoglin_stable/starting_pieces", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/starting_stairs_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/starting_stairs_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/starting_stairs_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/starting_stairs_3", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/starting_stairs_4", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/mirrored_starting_pieces", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/stairs_0_mirrored", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/stairs_1_mirrored", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/stairs_2_mirrored", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/stairs_3_mirrored", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/starting_pieces/stairs_4_mirrored", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/wall_bases", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/walls/wall_base", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/walls", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/walls/side_wall_0", $$3), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/walls/side_wall_1", $$3), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/stairs", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_1_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_1_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_1_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_1_3", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_1_4", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_2_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_2_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_2_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_2_3", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_2_4", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_3_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_3_1", $$2), (Object)1), (Object[])new Pair[]{Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_3_2", $$2), (Object)1), Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_3_3", $$2), (Object)1), Pair.of(dth.b("bastion/hoglin_stable/stairs/stairs_3_4", $$2), (Object)1)}), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/small_stables/inner", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/inner_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/inner_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/inner_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/inner_3", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/small_stables/outer", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/outer_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/outer_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/outer_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/small_stables/outer_3", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/large_stables/inner", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/inner_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/inner_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/inner_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/inner_3", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/inner_4", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/large_stables/outer", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/outer_0", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/outer_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/outer_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/outer_3", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/large_stables/outer_4", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/posts", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/posts/stair_post", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/posts/end_post", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/ramparts", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/ramparts/ramparts_1", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/ramparts/ramparts_2", $$2), (Object)1), (Object)Pair.of(dth.b("bastion/hoglin_stable/ramparts/ramparts_3", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/rampart_plates", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/rampart_plates/rampart_plate_1", $$2), (Object)1)), dtj.a.b));
        nt.a($$0, "bastion/hoglin_stable/connectors", new dtj($$5, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.b("bastion/hoglin_stable/connectors/end_post_connector", $$2), (Object)1)), dtj.a.b));
    }
}

