/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class no {
    public static final acp<dtj> a = nt.a("village/desert/town_centers");
    private static final acp<dtj> b = nt.a("village/desert/terminators");
    private static final acp<dtj> c = nt.a("village/desert/zombie/terminators");

    public static void a(nm<dtj> $$0) {
        hf<dre> $$1 = $$0.a(jc.ay);
        he.c<dre> $$2 = $$1.b(pe.j);
        he.c<dre> $$3 = $$1.b(pe.a);
        hf<dvr> $$4 = $$0.a(jc.aA);
        he.c<dvr> $$5 = $$4.b(nu.e);
        he.c<dvr> $$6 = $$4.b(nu.p);
        hf<dtj> $$7 = $$0.a(jc.aC);
        he.c<dtj> $$8 = $$7.b(nt.a);
        he.c<dtj> $$9 = $$7.b(b);
        he.c<dtj> $$10 = $$7.b(c);
        $$0.a(a, new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/town_centers/desert_meeting_point_1"), (Object)98), (Object)Pair.of(dth.a("village/desert/town_centers/desert_meeting_point_2"), (Object)98), (Object)Pair.of(dth.a("village/desert/town_centers/desert_meeting_point_3"), (Object)49), (Object)Pair.of(dth.a("village/desert/zombie/town_centers/desert_meeting_point_1", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/town_centers/desert_meeting_point_2", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/town_centers/desert_meeting_point_3", $$5), (Object)1)), dtj.a.b));
        nt.a($$0, "village/desert/streets", new dtj($$9, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/streets/corner_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/corner_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/straight_01"), (Object)4), (Object)Pair.of(dth.a("village/desert/streets/straight_02"), (Object)4), (Object)Pair.of(dth.a("village/desert/streets/straight_03"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/crossroad_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/crossroad_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/crossroad_03"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/square_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/square_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/streets/turn_01"), (Object)3)), dtj.a.a));
        nt.a($$0, "village/desert/zombie/streets", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/zombie/streets/corner_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/corner_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/straight_01"), (Object)4), (Object)Pair.of(dth.a("village/desert/zombie/streets/straight_02"), (Object)4), (Object)Pair.of(dth.a("village/desert/zombie/streets/straight_03"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/crossroad_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/crossroad_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/crossroad_03"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/square_01"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/square_02"), (Object)3), (Object)Pair.of(dth.a("village/desert/zombie/streets/turn_01"), (Object)3)), dtj.a.a));
        nt.a($$0, "village/desert/houses", new dtj($$9, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/houses/desert_small_house_1"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_2"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_3"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_4"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_5"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_6"), (Object)1), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_7"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_small_house_8"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_medium_house_1"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_medium_house_2"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_butcher_shop_1"), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_tool_smith_1"), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/desert/houses/desert_fletcher_house_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_shepherd_house_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_armorer_1"), (Object)1), Pair.of(dth.a("village/desert/houses/desert_fisher_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_tannery_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_cartographer_house_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_library_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_mason_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_weaponsmith_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_temple_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_temple_2"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_large_farm_1", $$6), (Object)11), Pair.of(dth.a("village/desert/houses/desert_farm_1", $$6), (Object)4), Pair.of(dth.a("village/desert/houses/desert_farm_2", $$6), (Object)4), Pair.of(dth.a("village/desert/houses/desert_animal_pen_1"), (Object)2), Pair.of(dth.a("village/desert/houses/desert_animal_pen_2"), (Object)2), Pair.of(dth.g(), (Object)5)}), dtj.a.b));
        nt.a($$0, "village/desert/zombie/houses", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_1", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_2", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_3", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_4", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_5", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_6", $$5), (Object)1), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_7", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_small_house_8", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_medium_house_1", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/zombie/houses/desert_medium_house_2", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_butcher_shop_1", $$5), (Object)2), (Object)Pair.of(dth.a("village/desert/houses/desert_tool_smith_1", $$5), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/desert/houses/desert_fletcher_house_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_shepherd_house_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_armorer_1", $$5), (Object)1), Pair.of(dth.a("village/desert/houses/desert_fisher_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_tannery_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_cartographer_house_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_library_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_mason_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_weaponsmith_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_temple_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_temple_2", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_large_farm_1", $$5), (Object)7), Pair.of(dth.a("village/desert/houses/desert_farm_1", $$5), (Object)4), Pair.of(dth.a("village/desert/houses/desert_farm_2", $$5), (Object)4), Pair.of(dth.a("village/desert/houses/desert_animal_pen_1", $$5), (Object)2), Pair.of(dth.a("village/desert/houses/desert_animal_pen_2", $$5), (Object)2), Pair.of(dth.g(), (Object)5)}), dtj.a.b));
        $$0.a(b, new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/terminators/terminator_01"), (Object)1), (Object)Pair.of(dth.a("village/desert/terminators/terminator_02"), (Object)1)), dtj.a.a));
        $$0.a(c, new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/terminators/terminator_01"), (Object)1), (Object)Pair.of(dth.a("village/desert/zombie/terminators/terminator_02"), (Object)1)), dtj.a.a));
        nt.a($$0, "village/desert/decor", new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/desert_lamp_1"), (Object)10), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.g(), (Object)10)), dtj.a.b));
        nt.a($$0, "village/desert/zombie/decor", new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/desert_lamp_1", $$5), (Object)10), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.g(), (Object)10)), dtj.a.b));
        nt.a($$0, "village/desert/villagers", new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/desert/villagers/baby"), (Object)1), (Object)Pair.of(dth.a("village/desert/villagers/unemployed"), (Object)10)), dtj.a.b));
        nt.a($$0, "village/desert/camel", new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/camel_spawn"), (Object)1)), dtj.a.b));
        nt.a($$0, "village/desert/zombie/villagers", new dtj($$8, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/desert/zombie/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/desert/zombie/villagers/unemployed"), (Object)10)), dtj.a.b));
    }
}

