/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class nv {
    public static final acp<dtj> a = nt.a("village/savanna/town_centers");
    private static final acp<dtj> b = nt.a("village/savanna/terminators");
    private static final acp<dtj> c = nt.a("village/savanna/zombie/terminators");

    public static void a(nm<dtj> $$0) {
        hf<dre> $$1 = $$0.a(jc.ay);
        he.c<dre> $$2 = $$1.b(pe.g);
        he.c<dre> $$3 = $$1.b(pe.a);
        he.c<dre> $$4 = $$1.b(pe.b);
        hf<dvr> $$5 = $$0.a(jc.aA);
        he.c<dvr> $$6 = $$5.b(nu.b);
        he.c<dvr> $$7 = $$5.b(nu.j);
        he.c<dvr> $$8 = $$5.b(nu.m);
        hf<dtj> $$9 = $$0.a(jc.aC);
        he.c<dtj> $$10 = $$9.b(nt.a);
        he.c<dtj> $$11 = $$9.b(b);
        he.c<dtj> $$12 = $$9.b(c);
        $$0.a(a, new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/town_centers/savanna_meeting_point_1"), (Object)100), (Object)Pair.of(dth.a("village/savanna/town_centers/savanna_meeting_point_2"), (Object)50), (Object)Pair.of(dth.a("village/savanna/town_centers/savanna_meeting_point_3"), (Object)150), (Object)Pair.of(dth.a("village/savanna/town_centers/savanna_meeting_point_4"), (Object)150), (Object)Pair.of(dth.a("village/savanna/zombie/town_centers/savanna_meeting_point_1", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/town_centers/savanna_meeting_point_2", $$6), (Object)1), (Object)Pair.of(dth.a("village/savanna/zombie/town_centers/savanna_meeting_point_3", $$6), (Object)3), (Object)Pair.of(dth.a("village/savanna/zombie/town_centers/savanna_meeting_point_4", $$6), (Object)3)), dtj.a.b));
        nt.a($$0, "village/savanna/streets", new dtj($$11, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/streets/corner_01", $$7), (Object)2), (Object)Pair.of(dth.a("village/savanna/streets/corner_03", $$7), (Object)2), (Object)Pair.of(dth.a("village/savanna/streets/straight_02", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/straight_04", $$7), (Object)7), (Object)Pair.of(dth.a("village/savanna/streets/straight_05", $$7), (Object)3), (Object)Pair.of(dth.a("village/savanna/streets/straight_06", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/straight_08", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/straight_09", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/straight_10", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/straight_11", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/streets/crossroad_02", $$7), (Object)1), (Object)Pair.of(dth.a("village/savanna/streets/crossroad_03", $$7), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/savanna/streets/crossroad_04", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/crossroad_05", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/crossroad_06", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/crossroad_07", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/split_01", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/split_02", $$7), (Object)2), Pair.of(dth.a("village/savanna/streets/turn_01", $$7), (Object)3)}), dtj.a.a));
        nt.a($$0, "village/savanna/zombie/streets", new dtj($$12, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/zombie/streets/corner_01", $$7), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/streets/corner_03", $$7), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_02", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_04", $$7), (Object)7), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_05", $$7), (Object)3), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_06", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_08", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_09", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_10", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/straight_11", $$7), (Object)4), (Object)Pair.of(dth.a("village/savanna/zombie/streets/crossroad_02", $$7), (Object)1), (Object)Pair.of(dth.a("village/savanna/zombie/streets/crossroad_03", $$7), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/savanna/zombie/streets/crossroad_04", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/crossroad_05", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/crossroad_06", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/crossroad_07", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/split_01", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/split_02", $$7), (Object)2), Pair.of(dth.a("village/savanna/zombie/streets/turn_01", $$7), (Object)3)}), dtj.a.a));
        nt.a($$0, "village/savanna/houses", new dtj($$11, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_1"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_2"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_3"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_4"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_5"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_6"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_7"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_small_house_8"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_medium_house_1"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_medium_house_2"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_butchers_shop_1"), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_butchers_shop_2"), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/savanna/houses/savanna_tool_smith_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_fletcher_house_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_shepherd_1"), (Object)7), Pair.of(dth.a("village/savanna/houses/savanna_armorer_1"), (Object)1), Pair.of(dth.a("village/savanna/houses/savanna_fisher_cottage_1"), (Object)3), Pair.of(dth.a("village/savanna/houses/savanna_tannery_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_cartographer_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_library_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_mason_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_weaponsmith_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_weaponsmith_2"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_temple_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_temple_2"), (Object)3), Pair.of(dth.a("village/savanna/houses/savanna_large_farm_1", $$8), (Object)4), Pair.of(dth.a("village/savanna/houses/savanna_large_farm_2", $$8), (Object)6), Pair.of(dth.a("village/savanna/houses/savanna_small_farm", $$8), (Object)4), Pair.of(dth.a("village/savanna/houses/savanna_animal_pen_1"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_animal_pen_2"), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_animal_pen_3"), (Object)2), Pair.of(dth.g(), (Object)5)}), dtj.a.b));
        nt.a($$0, "village/savanna/zombie/houses", new dtj($$12, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_1", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_2", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_3", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_4", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_5", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_6", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_7", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_small_house_8", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_medium_house_1", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/zombie/houses/savanna_medium_house_2", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_butchers_shop_1", $$6), (Object)2), (Object)Pair.of(dth.a("village/savanna/houses/savanna_butchers_shop_2", $$6), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/savanna/houses/savanna_tool_smith_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_fletcher_house_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_shepherd_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_armorer_1", $$6), (Object)1), Pair.of(dth.a("village/savanna/houses/savanna_fisher_cottage_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_tannery_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_cartographer_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_library_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_mason_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_weaponsmith_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_weaponsmith_2", $$6), (Object)2), Pair.of(dth.a("village/savanna/houses/savanna_temple_1", $$6), (Object)1), Pair.of(dth.a("village/savanna/houses/savanna_temple_2", $$6), (Object)3), Pair.of(dth.a("village/savanna/houses/savanna_large_farm_1", $$6), (Object)4), Pair.of(dth.a("village/savanna/zombie/houses/savanna_large_farm_2", $$6), (Object)4), Pair.of(dth.a("village/savanna/houses/savanna_small_farm", $$6), (Object)4), Pair.of(dth.a("village/savanna/houses/savanna_animal_pen_1", $$6), (Object)2), Pair.of(dth.a("village/savanna/zombie/houses/savanna_animal_pen_2", $$6), (Object)2), Pair.of(dth.a("village/savanna/zombie/houses/savanna_animal_pen_3", $$6), (Object)2), Pair.of(dth.g(), (Object)5)}), dtj.a.b));
        $$0.a(b, new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/plains/terminators/terminator_01", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_02", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_03", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_04", $$7), (Object)1), (Object)Pair.of(dth.a("village/savanna/terminators/terminator_05", $$7), (Object)1)), dtj.a.a));
        $$0.a(c, new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/plains/terminators/terminator_01", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_02", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_03", $$7), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_04", $$7), (Object)1), (Object)Pair.of(dth.a("village/savanna/zombie/terminators/terminator_05", $$7), (Object)1)), dtj.a.a));
        nt.a($$0, "village/savanna/trees", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a($$2), (Object)1)), dtj.a.b));
        nt.a($$0, "village/savanna/decor", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/savanna_lamp_post_01"), (Object)4), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.a($$4), (Object)1), (Object)Pair.of(dth.g(), (Object)4)), dtj.a.b));
        nt.a($$0, "village/savanna/zombie/decor", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/savanna_lamp_post_01", $$6), (Object)4), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.a($$4), (Object)1), (Object)Pair.of(dth.g(), (Object)4)), dtj.a.b));
        nt.a($$0, "village/savanna/villagers", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/savanna/villagers/baby"), (Object)1), (Object)Pair.of(dth.a("village/savanna/villagers/unemployed"), (Object)10)), dtj.a.b));
        nt.a($$0, "village/savanna/zombie/villagers", new dtj($$10, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/savanna/zombie/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/savanna/zombie/villagers/unemployed"), (Object)10)), dtj.a.b));
    }
}

