/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class oa {
    public static final acp<dtj> a = nt.a("village/taiga/town_centers");
    private static final acp<dtj> b = nt.a("village/taiga/terminators");

    public static void a(nm<dtj> $$0) {
        hf<dre> $$1 = $$0.a(jc.ay);
        he.c<dre> $$2 = $$1.b(pe.h);
        he.c<dre> $$3 = $$1.b(pe.i);
        he.c<dre> $$4 = $$1.b(pe.e);
        he.c<dre> $$5 = $$1.b(pe.l);
        he.c<dre> $$6 = $$1.b(pe.m);
        hf<dvr> $$7 = $$0.a(jc.aA);
        he.c<dvr> $$8 = $$7.b(nu.f);
        he.c<dvr> $$9 = $$7.b(nu.d);
        he.c<dvr> $$10 = $$7.b(nu.k);
        he.c<dvr> $$11 = $$7.b(nu.o);
        hf<dtj> $$12 = $$0.a(jc.aC);
        he.c<dtj> $$13 = $$12.b(nt.a);
        he.c<dtj> $$14 = $$12.b(b);
        $$0.a(a, new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/town_centers/taiga_meeting_point_1", $$8), (Object)49), (Object)Pair.of(dth.a("village/taiga/town_centers/taiga_meeting_point_2", $$8), (Object)49), (Object)Pair.of(dth.a("village/taiga/zombie/town_centers/taiga_meeting_point_1", $$9), (Object)1), (Object)Pair.of(dth.a("village/taiga/zombie/town_centers/taiga_meeting_point_2", $$9), (Object)1)), dtj.a.b));
        nt.a($$0, "village/taiga/streets", new dtj($$14, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/streets/corner_01", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/streets/corner_02", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/streets/corner_03", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/streets/straight_01", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/streets/straight_02", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/streets/straight_03", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/streets/straight_04", $$10), (Object)7), (Object)Pair.of(dth.a("village/taiga/streets/straight_05", $$10), (Object)7), (Object)Pair.of(dth.a("village/taiga/streets/straight_06", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/streets/crossroad_01", $$10), (Object)1), (Object)Pair.of(dth.a("village/taiga/streets/crossroad_02", $$10), (Object)1), (Object)Pair.of(dth.a("village/taiga/streets/crossroad_03", $$10), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/taiga/streets/crossroad_04", $$10), (Object)2), Pair.of(dth.a("village/taiga/streets/crossroad_05", $$10), (Object)2), Pair.of(dth.a("village/taiga/streets/crossroad_06", $$10), (Object)2), Pair.of(dth.a("village/taiga/streets/turn_01", $$10), (Object)3)}), dtj.a.a));
        nt.a($$0, "village/taiga/zombie/streets", new dtj($$14, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/zombie/streets/corner_01", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/streets/corner_02", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/streets/corner_03", $$10), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_01", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_02", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_03", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_04", $$10), (Object)7), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_05", $$10), (Object)7), (Object)Pair.of(dth.a("village/taiga/zombie/streets/straight_06", $$10), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/streets/crossroad_01", $$10), (Object)1), (Object)Pair.of(dth.a("village/taiga/zombie/streets/crossroad_02", $$10), (Object)1), (Object)Pair.of(dth.a("village/taiga/zombie/streets/crossroad_03", $$10), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/taiga/zombie/streets/crossroad_04", $$10), (Object)2), Pair.of(dth.a("village/taiga/zombie/streets/crossroad_05", $$10), (Object)2), Pair.of(dth.a("village/taiga/zombie/streets/crossroad_06", $$10), (Object)2), Pair.of(dth.a("village/taiga/zombie/streets/turn_01", $$10), (Object)3)}), dtj.a.a));
        nt.a($$0, "village/taiga/houses", new dtj($$14, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/houses/taiga_small_house_1", $$8), (Object)4), (Object)Pair.of(dth.a("village/taiga/houses/taiga_small_house_2", $$8), (Object)4), (Object)Pair.of(dth.a("village/taiga/houses/taiga_small_house_3", $$8), (Object)4), (Object)Pair.of(dth.a("village/taiga/houses/taiga_small_house_4", $$8), (Object)4), (Object)Pair.of(dth.a("village/taiga/houses/taiga_small_house_5", $$8), (Object)4), (Object)Pair.of(dth.a("village/taiga/houses/taiga_medium_house_1", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_medium_house_2", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_medium_house_3", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_medium_house_4", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_butcher_shop_1", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_tool_smith_1", $$8), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_fletcher_house_1", $$8), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/taiga/houses/taiga_shepherds_house_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_armorer_house_1", $$8), (Object)1), Pair.of(dth.a("village/taiga/houses/taiga_armorer_2", $$8), (Object)1), Pair.of(dth.a("village/taiga/houses/taiga_fisher_cottage_1", $$8), (Object)3), Pair.of(dth.a("village/taiga/houses/taiga_tannery_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_cartographer_house_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_library_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_masons_house_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_weaponsmith_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_weaponsmith_2", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_temple_1", $$8), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_large_farm_1", $$11), (Object)6), Pair.of(dth.a("village/taiga/houses/taiga_large_farm_2", $$11), (Object)6), Pair.of(dth.a("village/taiga/houses/taiga_small_farm_1", $$8), (Object)1), Pair.of(dth.a("village/taiga/houses/taiga_animal_pen_1", $$8), (Object)2), Pair.of(dth.g(), (Object)6)}), dtj.a.b));
        nt.a($$0, "village/taiga/zombie/houses", new dtj($$14, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_small_house_1", $$9), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_small_house_2", $$9), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_small_house_3", $$9), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_small_house_4", $$9), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_small_house_5", $$9), (Object)4), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_medium_house_1", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_medium_house_2", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_medium_house_3", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_medium_house_4", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_butcher_shop_1", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/zombie/houses/taiga_tool_smith_1", $$9), (Object)2), (Object)Pair.of(dth.a("village/taiga/houses/taiga_fletcher_house_1", $$9), (Object)2), (Object[])new Pair[]{Pair.of(dth.a("village/taiga/zombie/houses/taiga_shepherds_house_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_armorer_house_1", $$9), (Object)1), Pair.of(dth.a("village/taiga/zombie/houses/taiga_fisher_cottage_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_tannery_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/zombie/houses/taiga_cartographer_house_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/zombie/houses/taiga_library_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_masons_house_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_weaponsmith_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/zombie/houses/taiga_weaponsmith_2", $$9), (Object)2), Pair.of(dth.a("village/taiga/zombie/houses/taiga_temple_1", $$9), (Object)2), Pair.of(dth.a("village/taiga/houses/taiga_large_farm_1", $$9), (Object)6), Pair.of(dth.a("village/taiga/zombie/houses/taiga_large_farm_2", $$9), (Object)6), Pair.of(dth.a("village/taiga/houses/taiga_small_farm_1", $$9), (Object)1), Pair.of(dth.a("village/taiga/houses/taiga_animal_pen_1", $$9), (Object)2), Pair.of(dth.g(), (Object)6)}), dtj.a.b));
        $$0.a(b, new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/plains/terminators/terminator_01", $$10), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_02", $$10), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_03", $$10), (Object)1), (Object)Pair.of(dth.a("village/plains/terminators/terminator_04", $$10), (Object)1)), dtj.a.a));
        nt.a($$0, "village/taiga/decor", new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/taiga_lamp_post_1"), (Object)10), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_1"), (Object)4), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_2"), (Object)1), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_3"), (Object)1), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_4"), (Object)1), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_5"), (Object)2), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_6"), (Object)1), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.a($$4), (Object)2), (Object)Pair.of(dth.a($$5), (Object)4), (Object)Pair.of(dth.a($$6), (Object)1), (Object[])new Pair[]{Pair.of(dth.g(), (Object)4)}), dtj.a.b));
        nt.a($$0, "village/taiga/zombie/decor", new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/taiga_decoration_1"), (Object)4), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_2"), (Object)1), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_3"), (Object)1), (Object)Pair.of(dth.a("village/taiga/taiga_decoration_4"), (Object)1), (Object)Pair.of(dth.a($$2), (Object)4), (Object)Pair.of(dth.a($$3), (Object)4), (Object)Pair.of(dth.a($$4), (Object)2), (Object)Pair.of(dth.a($$5), (Object)4), (Object)Pair.of(dth.a($$6), (Object)1), (Object)Pair.of(dth.g(), (Object)4)), dtj.a.b));
        nt.a($$0, "village/taiga/villagers", new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/taiga/villagers/baby"), (Object)1), (Object)Pair.of(dth.a("village/taiga/villagers/unemployed"), (Object)10)), dtj.a.b));
        nt.a($$0, "village/taiga/zombie/villagers", new dtj($$13, (List<Pair<Function<dtj.a, ? extends dth>, Integer>>)ImmutableList.of((Object)Pair.of(dth.a("village/taiga/zombie/villagers/nitwit"), (Object)1), (Object)Pair.of(dth.a("village/taiga/zombie/villagers/unemployed"), (Object)10)), dtj.a.b));
    }
}

