/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.mojang.datafixers.util.Pair
 */
import com.mojang.datafixers.util.Pair;
import java.util.List;

public class oc {
    public static final acp<dtj> a = nt.a("trail_ruins/tower");

    public static void a(nm<dtj> $$0) {
        hf<dtj> $$1 = $$0.a(jc.aC);
        he.c<dtj> $$2 = $$1.b(nt.a);
        hf<dvr> $$3 = $$0.a(jc.aA);
        he.c<dvr> $$4 = $$3.b(nu.J);
        he.c<dvr> $$5 = $$3.b(nu.K);
        he.c<dvr> $$6 = $$3.b(nu.L);
        $$0.a(a, new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/tower/tower_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_5", $$4), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/tower/tower_top", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/tower/tower_top_1", $$6), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_top_2", $$6), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_top_3", $$6), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_top_4", $$6), (Object)1), Pair.of(dth.b("trail_ruins/tower/tower_top_5", $$6), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/tower/additions", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/tower/hall_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/hall_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/hall_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/hall_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/hall_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/large_hall_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/large_hall_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/large_hall_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/large_hall_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/large_hall_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/one_room_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/one_room_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/one_room_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/one_room_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/one_room_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/platform_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/platform_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/platform_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/platform_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/platform_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/stable_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/stable_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/stable_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/stable_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/tower/stable_5", $$4), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/roads", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/roads/long_road_end", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_end_1", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_section_1", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_section_2", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_section_3", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_section_4", $$5), (Object)1), Pair.of(dth.b("trail_ruins/roads/road_spacer_1", $$5), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/buildings", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/buildings/group_hall_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_hall_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_hall_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_hall_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_hall_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/large_room_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/large_room_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/large_room_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/large_room_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/large_room_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/one_room_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/one_room_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/one_room_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/one_room_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/one_room_5", $$4), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/buildings/grouped", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/buildings/group_full_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_full_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_full_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_full_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_full_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_lower_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_lower_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_lower_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_lower_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_lower_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_upper_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_upper_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_upper_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_upper_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_upper_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_room_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_room_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_room_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_room_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/buildings/group_room_5", $$4), (Object)1)), dtj.a.b));
        nt.a($$0, "trail_ruins/decor", new dtj($$2, List.of(Pair.of(dth.b("trail_ruins/decor/decor_1", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_2", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_3", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_4", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_5", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_6", $$4), (Object)1), Pair.of(dth.b("trail_ruins/decor/decor_7", $$4), (Object)1)), dtj.a.b));
    }
}

