modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/Yesssssman/epicfightmod/issues" #optional
[[mods]] #mandatory
modId="epicfight" #mandatory
version="20.12.6" #mandatory
displayName="Epic Fight" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod" #optional
logoFile="epicfight_logo.png" #optional
credits="METAL, SAGESSE, Nathan" #optional
authors="Yesman(a.k.a maninthe_home)" #optional
description='''Fight til u dead'''

[[dependencies.epicfight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.4.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
